// PMS酒店管理系统 首页 首页 今日预抵（散客）
export const PMS_HOMEPAGE_HOMEPAGE_INDIVIDUALAPPROACHING = 'PMS_HOMEPAGE_HOMEPAGE_INDIVIDUALAPPROACHING';

// PMS酒店管理系统 首页 首页 今日已抵（散客）
export const PMS_HOMEPAGE_HOMEPAGE_INDIVIDUALARRIVEL = 'PMS_HOMEPAGE_HOMEPAGE_INDIVIDUALARRIVEL';

// PMS酒店管理系统 首页 首页 今日预抵（团队）
export const PMS_HOMEPAGE_HOMEPAGE_GROUPAPPROACHING = 'PMS_HOMEPAGE_HOMEPAGE_GROUPAPPROACHING';

// PMS酒店管理系统 首页 首页 今日已抵（团队）
export const PMS_HOMEPAGE_HOMEPAGE_GROUPARRIVEL = 'PMS_HOMEPAGE_HOMEPAGE_GROUPARRIVEL';

// PMS酒店管理系统 首页 首页 今日预离房间
export const PMS_HOMEPAGE_HOMEPAGE_SOONTOLEAVE = 'PMS_HOMEPAGE_HOMEPAGE_SOONTOLEAVE';

// PMS酒店管理系统 首页 首页 在住房间
export const PMS_HOMEPAGE_HOMEPAGE_LIVINGIN = 'PMS_HOMEPAGE_HOMEPAGE_LIVINGIN';

// PMS酒店管理系统 首页 首页 夜审
export const PMS_HOMEPAGE_HOMEPAGE_TONIGHTTRIAL = 'PMS_HOMEPAGE_HOMEPAGE_TONIGHTTRIAL';

// PMS酒店管理系统 首页 首页 散客步入
export const PMS_HOMEPAGE_HOMEPAGE_INDIVIDUALCHECKIN = 'PMS_HOMEPAGE_HOMEPAGE_INDIVIDUALCHECKIN';

// PMS酒店管理系统 首页 首页 散客预订
export const PMS_HOMEPAGE_HOMEPAGE_INDIVIDUALRESERVE = 'PMS_HOMEPAGE_HOMEPAGE_INDIVIDUALRESERVE';

// PMS酒店管理系统 首页 首页 团队预订
export const PMS_HOMEPAGE_HOMEPAGE_GROUPRESERVE = 'PMS_HOMEPAGE_HOMEPAGE_GROUPRESERVE';

// PMS酒店管理系统 房态管理 房态管理-今日房态 查看列表
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_LIST = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_LIST';

// PMS酒店管理系统 房态管理 房态管理-今日房态 散客入住 同入住登记单新建权限
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_INDIVIDUALCHECKIN = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_INDIVIDUALCHECKIN';

// PMS酒店管理系统 房态管理 房态管理-今日房态 房间维修 同维修管理新建维修单
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_MAINTENANCE = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_MAINTENANCE';

// PMS酒店管理系统 房态管理 房态管理-今日房态 修改维修/完成维修 同维修管理完成维修单
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_REVISEMAINTENANCE = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_REVISEMAINTENANCE';

// PMS酒店管理系统 房态管理 房态管理-今日房态 房间自留
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_RETENTION = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_RETENTION';

// PMS酒店管理系统 房态管理 房态管理-今日房态 修改自留/结束自留
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_REVISERETENTION = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_REVISERETENTION';

// PMS酒店管理系统 房态管理 房态管理-今日房态 房间预订 同预订登记单新建权限
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_INDIVIDUALRESERVE = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_INDIVIDUALRESERVE';

// PMS酒店管理系统 房态管理 房态管理-今日房态 查看预订详情 同预订登记单编辑权限
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_RESERVATIONDETAILS = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_RESERVATIONDETAILS';

// PMS酒店管理系统 房态管理 房态管理-今日房态 预订抵达 同预订登记单预订抵达权限
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_ARRIVEL = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_ARRIVEL';

// PMS酒店管理系统 房态管理 房态管理-今日房态 取消预订 同预订登记单预订取消权限
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_CANCEL = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_CANCEL';

// PMS酒店管理系统 房态管理 房态管理-今日房态 查看登记详情 同入住登记单编辑权限
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_CHECKINDETAILS = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_CHECKINDETAILS';

// PMS酒店管理系统 房态管理 房态管理-今日房态 房间延住 同入住登记单延住权限
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_EXTEND = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_EXTEND';

// PMS酒店管理系统 房态管理 房态管理-今日房态 结账退房 同入住登记单退房权限
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_VACATE = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_VACATE';

// PMS酒店管理系统 房态管理 房态管理-今日房态 设置为脏房/打扫干净
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_CLEAN = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_CLEAN';

// PMS酒店管理系统 房态管理 房态管理-今日房态 新增叫醒/取消叫醒
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_WAKEUP = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_WAKEUP';

// PMS酒店管理系统 房态管理 房态管理-今日房态 房间锁定/解除锁定
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_LOCK = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_LOCK';

// PMS酒店管理系统 房态管理 房态管理-今日房态 查看未来预订单 同预订登记单编辑权限
export const PMS_ROOMSTATUS_TODAYROOMSTATUS_FUTURERESERVATION = 'PMS_ROOMSTATUS_TODAYROOMSTATUS_FUTURERESERVATION';

// PMS酒店管理系统 房态管理 房态管理-远期房态 查看列表
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_LIST = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_LIST';

// PMS酒店管理系统 房态管理 房态管理-远期房态 房间维修 同维修管理新建维修单
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_MAINTENANCE = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_MAINTENANCE';

// PMS酒店管理系统 房态管理 房态管理-远期房态 房间自留 同今日房态房间自留权限
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_RETENTION = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_RETENTION';

// PMS酒店管理系统 房态管理 房态管理-远期房态 房间预订 同预订登记单新建权限
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_ROOMRESERVATION = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_ROOMRESERVATION';

// PMS酒店管理系统 房态管理 房态管理-远期房态 查看预订详情 同预订登记单编辑权限
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_RESERVATIONDETAILS = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_RESERVATIONDETAILS';

// PMS酒店管理系统 房态管理 房态管理-远期房态 预订抵达 同预订登记单预订抵达权限
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_ARRIVEL = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_ARRIVEL';

// PMS酒店管理系统 房态管理 房态管理-远期房态 取消预订 同预订登记单预订取消权限
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_CANCEL = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_CANCEL';

// PMS酒店管理系统 房态管理 房态管理-远期房态 查看登记详情 同入住登记单编辑权限
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_REGISTERDETAILS = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_REGISTERDETAILS';

// PMS酒店管理系统 房态管理 房态管理-远期房态 房间延住 同入住登记单延住权限
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_EXTEND = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_EXTEND';

// PMS酒店管理系统 房态管理 房态管理-远期房态 结账退房 同入住登记单退房权限
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_VACATE = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_VACATE';

// PMS酒店管理系统 房态管理 房态管理-远期房态 修改维修/完成维修 同维修管理完成维修单
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_REVISEMAINTENANCE = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_REVISEMAINTENANCE';

// PMS酒店管理系统 房态管理 房态管理-远期房态 修改自留/结束自留 同今日房态房间结束自留权限
export const PMS_ROOMSTATUS_FORWARDROOMSTATUS_REVISERETENTION = 'PMS_ROOMSTATUS_FORWARDROOMSTATUS_REVISERETENTION';

// PMS酒店管理系统 房态管理 房态管理-维修单管理 查看列表
export const PMS_ROOMSTATUS_MAINTENANCEBILL_LIST = 'PMS_ROOMSTATUS_MAINTENANCEBILL_LIST';

// PMS酒店管理系统 房态管理 房态管理-维修单管理 新增维修
export const PMS_ROOMSTATUS_MAINTENANCEBILL_ADD = 'PMS_ROOMSTATUS_MAINTENANCEBILL_ADD';

// PMS酒店管理系统 房态管理 房态管理-维修单管理 导出
export const PMS_ROOMSTATUS_MAINTENANCEBILL_EXPORT = 'PMS_ROOMSTATUS_MAINTENANCEBILL_EXPORT';

// PMS酒店管理系统 房态管理 房态管理-维修单管理 修改维修/完成维修/取消维修
export const PMS_ROOMSTATUS_MAINTENANCEBILL_REVISEMAINTENANCE = 'PMS_ROOMSTATUS_MAINTENANCEBILL_REVISEMAINTENANCE';

// PMS酒店管理系统 入住管理 入住管理-散客预订 列表
export const PMS_CHECKIN_INDIVIDUALRESERVATION_LIST = 'PMS_CHECKIN_INDIVIDUALRESERVATION_LIST';

// PMS酒店管理系统 入住管理 入住管理-散客预订 散客预订
export const PMS_CHECKIN_INDIVIDUALRESERVATION_INDIVIDUALRESERVE = 'PMS_CHECKIN_INDIVIDUALRESERVATION_INDIVIDUALRESERVE';

// PMS酒店管理系统 入住管理 入住管理-散客预订 修改/排房号/入住/查看
export const PMS_CHECKIN_INDIVIDUALRESERVATION_EDIT = 'PMS_CHECKIN_INDIVIDUALRESERVATION_EDIT';

// PMS酒店管理系统 入住管理 入住管理-散客预订 取消
export const PMS_CHECKIN_INDIVIDUALRESERVATION_CANCEL = 'PMS_CHECKIN_INDIVIDUALRESERVATION_CANCEL';

// PMS酒店管理系统 入住管理 入住管理-散客预订 延到
export const PMS_CHECKIN_INDIVIDUALRESERVATION_DELAY = 'PMS_CHECKIN_INDIVIDUALRESERVATION_DELAY';

// PMS酒店管理系统 入住管理 入住管理-散客预订 打印
export const PMS_CHECKIN_INDIVIDUALRESERVATION_PRINT = 'PMS_CHECKIN_INDIVIDUALRESERVATION_PRINT';

// PMS酒店管理系统 入住管理 入住管理-散客预订 noshow
export const PMS_CHECKIN_INDIVIDUALRESERVATION_NOSHOW = 'PMS_CHECKIN_INDIVIDUALRESERVATION_NOSHOW';

// PMS酒店管理系统 入住管理 入住管理-散客预订 导出
export const PMS_CHECKIN_INDIVIDUALRESERVATION_EXPORT = 'PMS_CHECKIN_INDIVIDUALRESERVATION_EXPORT';

// PMS酒店管理系统 入住管理 入住管理-团队预订 列表
export const PMS_CHECKIN_GROUPRESERVATION_LIST = 'PMS_CHECKIN_GROUPRESERVATION_LIST';

// PMS酒店管理系统 入住管理 入住管理-团队预订 团队预定
export const PMS_CHECKIN_GROUPRESERVATION_GROUPRESERVE = 'PMS_CHECKIN_GROUPRESERVATION_GROUPRESERVE';

// PMS酒店管理系统 入住管理 入住管理-团队预订 修改/排房号/入住/查看
export const PMS_CHECKIN_GROUPRESERVATION_EDIT = 'PMS_CHECKIN_GROUPRESERVATION_EDIT';

// PMS酒店管理系统 入住管理 入住管理-团队预订 开发票
export const PMS_CHECKIN_GROUPRESERVATION_INVOICE = 'PMS_CHECKIN_GROUPRESERVATION_INVOICE';

// PMS酒店管理系统 入住管理 入住管理-团队预订 退房
export const PMS_CHECKIN_GROUPRESERVATION_VACATE = 'PMS_CHECKIN_GROUPRESERVATION_VACATE';

// PMS酒店管理系统 入住管理 入住管理-团队预订 补结账
export const PMS_CHECKIN_GROUPRESERVATION_SUPPLYACCOUNT = 'PMS_CHECKIN_GROUPRESERVATION_SUPPLYACCOUNT';

// PMS酒店管理系统 入住管理 入住管理-团队预订 取消
export const PMS_CHECKIN_GROUPRESERVATION_CANCEL = 'PMS_CHECKIN_GROUPRESERVATION_CANCEL';

// PMS酒店管理系统 入住管理 入住管理-团队预订 延到
export const PMS_CHECKIN_GROUPRESERVATION_DELAY = 'PMS_CHECKIN_GROUPRESERVATION_DELAY';

// PMS酒店管理系统 入住管理 入住管理-团队预订 打印
export const PMS_CHECKIN_GROUPRESERVATION_PRINT = 'PMS_CHECKIN_GROUPRESERVATION_PRINT';

// PMS酒店管理系统 入住管理 入住管理-团队预订 noshow
export const PMS_CHECKIN_GROUPRESERVATION_NOSHOW = 'PMS_CHECKIN_GROUPRESERVATION_NOSHOW';

// PMS酒店管理系统 入住管理 入住管理-团队预订 导出
export const PMS_CHECKIN_GROUPRESERVATION_EXPORT = 'PMS_CHECKIN_GROUPRESERVATION_EXPORT';

// PMS酒店管理系统 入住管理 入住管理-入住登记 列表
export const PMS_CHECKIN_CHECKINREGISTER_LIST = 'PMS_CHECKIN_CHECKINREGISTER_LIST';

// PMS酒店管理系统 入住管理 入住管理-入住登记 散客步入
export const PMS_CHECKIN_CHECKINREGISTER_INDIVIDUALCHECKIN = 'PMS_CHECKIN_CHECKINREGISTER_INDIVIDUALCHECKIN';

// PMS酒店管理系统 入住管理 入住管理-入住登记 修改/添加费用
export const PMS_CHECKIN_CHECKINREGISTER_EDIT = 'PMS_CHECKIN_CHECKINREGISTER_EDIT';

// PMS酒店管理系统 入住管理 入住管理-入住登记 退房
export const PMS_CHECKIN_CHECKINREGISTER_VACATE = 'PMS_CHECKIN_CHECKINREGISTER_VACATE';

// PMS酒店管理系统 入住管理 入住管理-入住登记 延住
export const PMS_CHECKIN_CHECKINREGISTER_EXTEND = 'PMS_CHECKIN_CHECKINREGISTER_EXTEND';

// PMS酒店管理系统 入住管理 入住管理-入住登记 联房
export const PMS_CHECKIN_CHECKINREGISTER_UNITEROOMS = 'PMS_CHECKIN_CHECKINREGISTER_UNITEROOMS';

// PMS酒店管理系统 入住管理 入住管理-入住登记 补结账
export const PMS_CHECKIN_CHECKINREGISTER_SUPPLYACCOUNT = 'PMS_CHECKIN_CHECKINREGISTER_SUPPLYACCOUNT';

// PMS酒店管理系统 入住管理 入住管理-入住登记 开发票
export const PMS_CHECKIN_CHECKINREGISTER_INVOICE = 'PMS_CHECKIN_CHECKINREGISTER_INVOICE';

// PMS酒店管理系统 入住管理 入住管理-入住登记 打印
export const PMS_CHECKIN_CHECKINREGISTER_PRINT = 'PMS_CHECKIN_CHECKINREGISTER_PRINT';

// PMS酒店管理系统 入住管理 入住管理-入住登记 导出
export const PMS_CHECKIN_CHECKINREGISTER_EXPORT = 'PMS_CHECKIN_CHECKINREGISTER_EXPORT';

// PMS酒店管理系统 收银 收银-临时挂账登记单列表 列表
export const PMS_ACCOUNT_ONACCOUNT_LIST = 'PMS_ACCOUNT_ONACCOUNT_LIST';

// PMS酒店管理系统 收银 收银-历史账务查询 列表
export const PMS_ACCOUNT_HISTORICALACCOUNT_LIST = 'PMS_ACCOUNT_HISTORICALACCOUNT_LIST';

// PMS酒店管理系统 收银 收银-历史账务查询 导出
export const PMS_ACCOUNT_HISTORICALACCOUNT_EXPORT = 'PMS_ACCOUNT_HISTORICALACCOUNT_EXPORT';

// PMS酒店管理系统 收银 收银-应收账号列表 列表
export const PMS_ACCOUNT_ACCOUNTRECEIVABLE_LIST = 'PMS_ACCOUNT_ACCOUNTRECEIVABLE_LIST';

// PMS酒店管理系统 收银 收银-应收账号列表 编辑
export const PMS_ACCOUNT_ACCOUNTRECEIVABLE_EDIT = 'PMS_ACCOUNT_ACCOUNTRECEIVABLE_EDIT';

// PMS酒店管理系统 收银 收银-应收账号列表 账务
export const PMS_ACCOUNT_ACCOUNTRECEIVABLE_ACCOUNTS = 'PMS_ACCOUNT_ACCOUNTRECEIVABLE_ACCOUNTS';

// PMS酒店管理系统 收银 收银-应收账号列表 删除
export const PMS_ACCOUNT_ACCOUNTRECEIVABLE_DELETE = 'PMS_ACCOUNT_ACCOUNTRECEIVABLE_DELETE';

// PMS酒店管理系统 收银 收银-应收账号列表 账务导出
export const PMS_ACCOUNT_ACCOUNTRECEIVABLE_ACCOUNTSEXPORT = 'PMS_ACCOUNT_ACCOUNTRECEIVABLE_ACCOUNTSEXPORT';

// PMS酒店管理系统 收银 收银-应收账号列表 结算
export const PMS_ACCOUNT_ACCOUNTRECEIVABLE_SETTLEMENT = 'PMS_ACCOUNT_ACCOUNTRECEIVABLE_SETTLEMENT';

// PMS酒店管理系统 收银 收银-应收账号列表 调账
export const PMS_ACCOUNT_ACCOUNTRECEIVABLE_ACCOUNTADJUSTMENT = 'PMS_ACCOUNT_ACCOUNTRECEIVABLE_ACCOUNTADJUSTMENT';

// PMS酒店管理系统 夜审 夜审 列表
export const PMS_NIGHTTRIAL_NIGHTTRIAL_LIST = 'PMS_NIGHTTRIAL_NIGHTTRIAL_LIST';

// PMS酒店管理系统 夜审 夜审 执行夜审
export const PMS_NIGHTTRIAL_NIGHTTRIAL_IMPLEMENT = 'PMS_NIGHTTRIAL_NIGHTTRIAL_IMPLEMENT';

// PMS酒店管理系统 渠道管理 渠道管理-渠道列表 列表
export const PMS_CHANNEL_CHANNELLIST_LIST = 'PMS_CHANNEL_CHANNELLIST_LIST';

// PMS酒店管理系统 渠道管理 渠道管理-渠道列表 启用
export const PMS_CHANNEL_CHANNELLIST_ENABLED = 'PMS_CHANNEL_CHANNELLIST_ENABLED';

// PMS酒店管理系统 渠道管理 渠道管理-渠道列表 禁用
export const PMS_CHANNEL_CHANNELLIST_DISABLE = 'PMS_CHANNEL_CHANNELLIST_DISABLE';

// PMS酒店管理系统 渠道管理 渠道管理-业务来源列表 列表
export const PMS_CHANNEL_BUSINESSSOURCES_LIST = 'PMS_CHANNEL_BUSINESSSOURCES_LIST';

// PMS酒店管理系统 渠道管理 渠道管理-业务来源列表 启用
export const PMS_CHANNEL_BUSINESSSOURCES_ENABLED = 'PMS_CHANNEL_BUSINESSSOURCES_ENABLED';

// PMS酒店管理系统 渠道管理 渠道管理-业务来源列表 禁用
export const PMS_CHANNEL_BUSINESSSOURCES_DISABLE = 'PMS_CHANNEL_BUSINESSSOURCES_DISABLE';

// PMS酒店管理系统 渠道管理 渠道管理-价格代码管理 查看列表
export const PMS_CHANNEL_PRICECODE_LIST = 'PMS_CHANNEL_PRICECODE_LIST';

// PMS酒店管理系统 渠道管理 渠道管理-价格代码管理 添加价格代码
export const PMS_CHANNEL_PRICECODE_ADD = 'PMS_CHANNEL_PRICECODE_ADD';

// PMS酒店管理系统 渠道管理 渠道管理-价格代码管理 启用/禁用
export const PMS_CHANNEL_PRICECODE_ENABLED = 'PMS_CHANNEL_PRICECODE_ENABLED';

// PMS酒店管理系统 渠道管理 渠道管理-价格代码管理 编辑
export const PMS_CHANNEL_PRICECODE_EDIT = 'PMS_CHANNEL_PRICECODE_EDIT';

// PMS酒店管理系统 渠道管理 渠道管理-价格代码管理 删除
export const PMS_CHANNEL_PRICECODE_DELETE = 'PMS_CHANNEL_PRICECODE_DELETE';

// PMS酒店管理系统 渠道管理 渠道管理-房价管理 查看列表
export const PMS_CHANNEL_ROOMRATE_LIST = 'PMS_CHANNEL_ROOMRATE_LIST';

// PMS酒店管理系统 渠道管理 渠道管理-房价管理 按价格代码设置
export const PMS_CHANNEL_ROOMRATE_PRICECODESETUP = 'PMS_CHANNEL_ROOMRATE_PRICECODESETUP';

// PMS酒店管理系统 渠道管理 渠道管理-房价管理 按房型设置
export const PMS_CHANNEL_ROOMRATE_ROOMSTYLESETUP = 'PMS_CHANNEL_ROOMRATE_ROOMSTYLESETUP';

// PMS酒店管理系统 渠道管理 渠道管理-房价管理 清除全部房价
export const PMS_CHANNEL_ROOMRATE_RESETALLROOMRATE = 'PMS_CHANNEL_ROOMRATE_RESETALLROOMRATE';

// PMS酒店管理系统 渠道管理 渠道管理-房价管理 清除某个房价
export const PMS_CHANNEL_ROOMRATE_RESETONEROOMRATE = 'PMS_CHANNEL_ROOMRATE_RESETONEROOMRATE';

// PMS酒店管理系统 报表中心 报表中心-收款日报表 列表
export const PMS_REPORTFORMS_RECELVABLESDAILY_LIST = 'PMS_REPORTFORMS_RECELVABLESDAILY_LIST';

// PMS酒店管理系统 报表中心 报表中心-收款日报表 下载报表
export const PMS_REPORTFORMS_RECELVABLESDAILY_DOWNLOAD = 'PMS_REPORTFORMS_RECELVABLESDAILY_DOWNLOAD';

// PMS酒店管理系统 报表中心 报表中心-入住分析表 列表
export const PMS_REPORTFORMS_CHECKINANALYSIS_LIST = 'PMS_REPORTFORMS_CHECKINANALYSIS_LIST';

// PMS酒店管理系统 报表中心 报表中心-入住分析表 下载报表
export const PMS_REPORTFORMS_CHECKINANALYSIS_DOWNLOAD = 'PMS_REPORTFORMS_CHECKINANALYSIS_DOWNLOAD';

// PMS酒店管理系统 基础设置 基础设置-组织管理 列表
export const PMS_BASICSETTING_ORGANIZATION_LIST = 'PMS_BASICSETTING_ORGANIZATION_LIST';

// PMS酒店管理系统 基础设置 基础设置-组织管理 新增组织
export const PMS_BASICSETTING_ORGANIZATION_ADD = 'PMS_BASICSETTING_ORGANIZATION_ADD';

// PMS酒店管理系统 基础设置 基础设置-组织管理 编辑信息
export const PMS_BASICSETTING_ORGANIZATION_EDIT = 'PMS_BASICSETTING_ORGANIZATION_EDIT';

// PMS酒店管理系统 基础设置 基础设置-组织管理 禁用组织
export const PMS_BASICSETTING_ORGANIZATION_DISABLE = 'PMS_BASICSETTING_ORGANIZATION_DISABLE';

// PMS酒店管理系统 基础设置 基础设置-组织管理 启用组织
export const PMS_BASICSETTING_ORGANIZATION_ENABLED = 'PMS_BASICSETTING_ORGANIZATION_ENABLED';

// PMS酒店管理系统 基础设置 基础设置-组织管理 删除组织
export const PMS_BASICSETTING_ORGANIZATION_DELETE = 'PMS_BASICSETTING_ORGANIZATION_DELETE';

// PMS酒店管理系统 基础设置 基础设置-部门管理 列表
export const PMS_BASICSETTING_DEPARTMENT_LIST = 'PMS_BASICSETTING_DEPARTMENT_LIST';

// PMS酒店管理系统 基础设置 基础设置-部门管理 新增部门
export const PMS_BASICSETTING_DEPARTMENT_ADD = 'PMS_BASICSETTING_DEPARTMENT_ADD';

// PMS酒店管理系统 基础设置 基础设置-部门管理 编辑信息
export const PMS_BASICSETTING_DEPARTMENT_EDIT = 'PMS_BASICSETTING_DEPARTMENT_EDIT';

// PMS酒店管理系统 基础设置 基础设置-部门管理 删除部门
export const PMS_BASICSETTING_DEPARTMENT_DELETE = 'PMS_BASICSETTING_DEPARTMENT_DELETE';

// PMS酒店管理系统 基础设置 基础设置-角色管理 列表
export const PMS_BASICSETTING_CHARACTER_LIST = 'PMS_BASICSETTING_CHARACTER_LIST';

// PMS酒店管理系统 基础设置 基础设置-角色管理 新建角色
export const PMS_BASICSETTING_CHARACTER_ADD = 'PMS_BASICSETTING_CHARACTER_ADD';

// PMS酒店管理系统 基础设置 基础设置-角色管理 查看权限
export const PMS_BASICSETTING_CHARACTER_CHECK = 'PMS_BASICSETTING_CHARACTER_CHECK';

// PMS酒店管理系统 基础设置 基础设置-角色管理 编辑信息
export const PMS_BASICSETTING_CHARACTER_EDIT = 'PMS_BASICSETTING_CHARACTER_EDIT';

// PMS酒店管理系统 基础设置 基础设置-角色管理 设置权限
export const PMS_BASICSETTING_CHARACTER_SETUP = 'PMS_BASICSETTING_CHARACTER_SETUP';

// PMS酒店管理系统 基础设置 基础设置-角色管理 删除
export const PMS_BASICSETTING_CHARACTER_DELETE = 'PMS_BASICSETTING_CHARACTER_DELETE';

// PMS酒店管理系统 基础设置 基础设置-账号管理 列表
export const PMS_BASICSETTING_ACCOUNT_LIST = 'PMS_BASICSETTING_ACCOUNT_LIST';

// PMS酒店管理系统 基础设置 基础设置-账号管理 新建账号
export const PMS_BASICSETTING_ACCOUNT_ADD = 'PMS_BASICSETTING_ACCOUNT_ADD';

// PMS酒店管理系统 基础设置 基础设置-账号管理 角色设置
export const PMS_BASICSETTING_ACCOUNT_SETUP = 'PMS_BASICSETTING_ACCOUNT_SETUP';

// PMS酒店管理系统 基础设置 基础设置-账号管理 编辑信息
export const PMS_BASICSETTING_ACCOUNT_EDIT = 'PMS_BASICSETTING_ACCOUNT_EDIT';

// PMS酒店管理系统 基础设置 基础设置-账号管理 禁用
export const PMS_BASICSETTING_ACCOUNT_DISABLE = 'PMS_BASICSETTING_ACCOUNT_DISABLE';

// PMS酒店管理系统 基础设置 基础设置-账号管理 启用
export const PMS_BASICSETTING_ACCOUNT_ENABLED = 'PMS_BASICSETTING_ACCOUNT_ENABLED';

// PMS酒店管理系统 基础设置 基础设置-账号管理 删除
export const PMS_BASICSETTING_ACCOUNT_DELETE = 'PMS_BASICSETTING_ACCOUNT_DELETE';

// PMS酒店管理系统 导出管理 导出管理-导出管理 列表
export const PMS_EXPORTMANAGEMENT_EXPORTMANAGEMENT_LIST = 'PMS_EXPORTMANAGEMENT_EXPORTMANAGEMENT_LIST';

// PMS酒店管理系统 收银 收银-应收账号列表 新增
export const PMS_ACCOUNT_ACCOUNTRECEIVABLE_ADD = 'PMS_ACCOUNT_ACCOUNTRECEIVABLE_ADD';

// PMS酒店管理系统 渠道管理 渠道管理-渠道列表 新增
export const PMS_CHANNEL_CHANNELLIST_ADD = 'PMS_CHANNEL_CHANNELLIST_ADD';

// PMS酒店管理系统 渠道管理 渠道管理-渠道列表 编辑
export const PMS_CHANNEL_CHANNELLIST_EDIT = 'PMS_CHANNEL_CHANNELLIST_EDIT';

// PMS酒店管理系统 渠道管理 渠道管理-渠道列表 删除
export const PMS_CHANNEL_CHANNELLIST_DELETE = 'PMS_CHANNEL_CHANNELLIST_DELETE';

// PMS酒店管理系统 渠道管理 渠道管理-业务来源列表 新增
export const PMS_CHANNEL_BUSINESSSOURCES_ADD = 'PMS_CHANNEL_BUSINESSSOURCES_ADD';

// PMS酒店管理系统 渠道管理 渠道管理-业务来源列表 编辑
export const PMS_CHANNEL_BUSINESSSOURCES_EDIT = 'PMS_CHANNEL_BUSINESSSOURCES_EDIT';

// PMS酒店管理系统 渠道管理 渠道管理-业务来源列表 删除
export const PMS_CHANNEL_BUSINESSSOURCES_DELETE = 'PMS_CHANNEL_BUSINESSSOURCES_DELETE';

// PMS酒店管理系统 用户管理 用户管理-业主管理 列表
export const PMS_USERMANAGEMENT_PROPRIETOR_LIST = 'PMS_USERMANAGEMENT_PROPRIETOR_LIST';

// PMS酒店管理系统 用户管理 用户管理-业主管理 新增业主
export const PMS_USERMANAGEMENT_PROPRIETOR_ADD = 'PMS_USERMANAGEMENT_PROPRIETOR_ADD';

// PMS酒店管理系统 用户管理 用户管理-业主管理 编辑
export const PMS_USERMANAGEMENT_PROPRIETOR_EDIT = 'PMS_USERMANAGEMENT_PROPRIETOR_EDIT';

// PMS酒店管理系统 房源管理 房源管理-楼栋管理 列表
export const PMS_ROOMRESOURCES_BUILDINGS_LIST = 'PMS_ROOMRESOURCES_BUILDINGS_LIST';

// PMS酒店管理系统 房源管理 房源管理-楼栋管理 新增楼栋
export const PMS_ROOMRESOURCES_BUILDINGS_ADD = 'PMS_ROOMRESOURCES_BUILDINGS_ADD';

// PMS酒店管理系统 房源管理 房源管理-楼栋管理 编辑
export const PMS_ROOMRESOURCES_BUILDINGS_EDIT = 'PMS_ROOMRESOURCES_BUILDINGS_EDIT';

// PMS酒店管理系统 房源管理 房源管理-楼栋管理 启用/禁用
export const PMS_ROOMRESOURCES_BUILDINGS_ENABLED = 'PMS_ROOMRESOURCES_BUILDINGS_ENABLED';

// PMS酒店管理系统 房源管理 房源管理-楼栋管理 删除
export const PMS_ROOMRESOURCES_BUILDINGS_DELETE = 'PMS_ROOMRESOURCES_BUILDINGS_DELETE';

// PMS酒店管理系统 房源管理 房源管理-楼层管理 列表
export const PMS_ROOMRESOURCES_FLOOR_LIST = 'PMS_ROOMRESOURCES_FLOOR_LIST';

// PMS酒店管理系统 房源管理 房源管理-楼层管理 新增楼层
export const PMS_ROOMRESOURCES_FLOOR_ADD = 'PMS_ROOMRESOURCES_FLOOR_ADD';

// PMS酒店管理系统 房源管理 房源管理-楼层管理 编辑
export const PMS_ROOMRESOURCES_FLOOR_EDIT = 'PMS_ROOMRESOURCES_FLOOR_EDIT';

// PMS酒店管理系统 房源管理 房源管理-楼层管理 启用/禁用
export const PMS_ROOMRESOURCES_FLOOR_ENABLED = 'PMS_ROOMRESOURCES_FLOOR_ENABLED';

// PMS酒店管理系统 房源管理 房源管理-楼层管理 删除
export const PMS_ROOMRESOURCES_FLOOR_DELETE = 'PMS_ROOMRESOURCES_FLOOR_DELETE';

// PMS酒店管理系统 房源管理 房源管理-房型管理 列表
export const PMS_ROOMRESOURCES_ROOMTYPES_LIST = 'PMS_ROOMRESOURCES_ROOMTYPES_LIST';

// PMS酒店管理系统 房源管理 房源管理-房型管理 新增房型
export const PMS_ROOMRESOURCES_ROOMTYPES_ADD = 'PMS_ROOMRESOURCES_ROOMTYPES_ADD';

// PMS酒店管理系统 房源管理 房源管理-房型管理 编辑
export const PMS_ROOMRESOURCES_ROOMTYPES_EDIT = 'PMS_ROOMRESOURCES_ROOMTYPES_EDIT';

// PMS酒店管理系统 房源管理 房源管理-房型管理 启用/禁用
export const PMS_ROOMRESOURCES_ROOMTYPES_ENABLED = 'PMS_ROOMRESOURCES_ROOMTYPES_ENABLED';

// PMS酒店管理系统 房源管理 房源管理-房型管理 删除
export const PMS_ROOMRESOURCES_ROOMTYPES_DELETE = 'PMS_ROOMRESOURCES_ROOMTYPES_DELETE';

// PMS酒店管理系统 房源管理 房源管理-房型管理 图片管理
export const PMS_ROOMRESOURCES_ROOMTYPES_PICTURES = 'PMS_ROOMRESOURCES_ROOMTYPES_PICTURES';

// PMS酒店管理系统 房源管理 房源管理-标签管理 列表
export const PMS_ROOMRESOURCES_TAG_LIST = 'PMS_ROOMRESOURCES_TAG_LIST';

// PMS酒店管理系统 房源管理 房源管理-标签管理 新增标签
export const PMS_ROOMRESOURCES_TAG_ADD = 'PMS_ROOMRESOURCES_TAG_ADD';

// PMS酒店管理系统 房源管理 房源管理-标签管理 编辑
export const PMS_ROOMRESOURCES_TAG_EDIT = 'PMS_ROOMRESOURCES_TAG_EDIT';

// PMS酒店管理系统 房源管理 房源管理-标签管理 启用/禁用
export const PMS_ROOMRESOURCES_TAG_ENABLED = 'PMS_ROOMRESOURCES_TAG_ENABLED';

// PMS酒店管理系统 房源管理 房源管理-标签管理 删除
export const PMS_ROOMRESOURCES_TAG_DELETE = 'PMS_ROOMRESOURCES_TAG_DELETE';

// PMS酒店管理系统 房源管理 房源管理-房间管理 列表
export const PMS_ROOMRESOURCES_ROOMMANAGEMENT_LIST = 'PMS_ROOMRESOURCES_ROOMMANAGEMENT_LIST';

// PMS酒店管理系统 房源管理 房源管理-房间管理 新增房间
export const PMS_ROOMRESOURCES_ROOMMANAGEMENT_ADD = 'PMS_ROOMRESOURCES_ROOMMANAGEMENT_ADD';

// PMS酒店管理系统 房源管理 房源管理-房间管理 编辑
export const PMS_ROOMRESOURCES_ROOMMANAGEMENT_EDIT = 'PMS_ROOMRESOURCES_ROOMMANAGEMENT_EDIT';

// PMS酒店管理系统 房源管理 房源管理-房间管理 启用/禁用
export const PMS_ROOMRESOURCES_ROOMMANAGEMENT_ENABLED = 'PMS_ROOMRESOURCES_ROOMMANAGEMENT_ENABLED';

// PMS酒店管理系统 房源管理 房源管理-房间管理 导出
export const PMS_ROOMRESOURCES_ROOMMANAGEMENT_EXPORT = 'PMS_ROOMRESOURCES_ROOMMANAGEMENT_EXPORT';

// PMS酒店管理系统 基础设置 基础设置-角色组管理 列表
export const PMS_BASICSETTING_CHARACTERGROUP_LIST = 'PMS_BASICSETTING_CHARACTERGROUP_LIST';

// PMS酒店管理系统 基础设置 基础设置-角色组管理 新增角色组
export const PMS_BASICSETTING_CHARACTERGROUP_ADD = 'PMS_BASICSETTING_CHARACTERGROUP_ADD';

// PMS酒店管理系统 基础设置 基础设置-角色组管理 编辑角色组
export const PMS_BASICSETTING_CHARACTERGROUP_EDIT = 'PMS_BASICSETTING_CHARACTERGROUP_EDIT';

// PMS酒店管理系统 基础设置 基础设置-收费类目设置 列表
export const PMS_BASICSETTING_CHARGECATEGORY_LIST = 'PMS_BASICSETTING_CHARGECATEGORY_LIST';

// PMS酒店管理系统 基础设置 基础设置-收费类目设置 编辑
export const PMS_BASICSETTING_CHARGECATEGORY_EDIT = 'PMS_BASICSETTING_CHARGECATEGORY_EDIT';

// PMS酒店管理系统 基础设置 基础设置-收费方式设置 列表
export const PMS_BASICSETTING_WAYSOFCHARGING_LIST = 'PMS_BASICSETTING_WAYSOFCHARGING_LIST';

// PMS酒店管理系统 基础设置 基础设置-收费方式设置 编辑
export const PMS_BASICSETTING_WAYSOFCHARGING_EDIT = 'PMS_BASICSETTING_WAYSOFCHARGING_EDIT';

/* 20181200 新增 */

// PMS酒店管理系统 入住管理 入住管理-服务单管理 列表 pms配合运营后台改动
export const PMS_CHECKIN_SERVICETICKET_LIST = 'PMS_CHECKIN_SERVICETICKET_LIST';

// PMS酒店管理系统 入住管理 入住管理-服务单管理 创建新服务
export const PMS_CHECKIN_SERVICETICKET_ADD = 'PMS_CHECKIN_SERVICETICKET_ADD';

// PMS酒店管理系统 入住管理 入住管理-服务单管理 导出
export const PMS_CHECKIN_SERVICETICKET_EXPORT = 'PMS_CHECKIN_SERVICETICKET_EXPORT';

// PMS酒店管理系统 入住管理 入住管理-服务单管理 分配
export const PMS_CHECKIN_SERVICETICKET_DISTRIBUTE = 'PMS_CHECKIN_SERVICETICKET_DISTRIBUTE';

// PMS酒店管理系统 入住管理 入住管理-服务单管理 删除
export const PMS_CHECKIN_SERVICETICKET_DELETE = 'PMS_CHECKIN_SERVICETICKET_DELETE';

// PMS酒店管理系统 基础设置 基础设置-服务项管理 列表
export const PMS_BASICSETTING_SERVICEITEM_LIST = 'PMS_BASICSETTING_SERVICEITEM_LIST';

// PMS酒店管理系统 基础设置 基础设置-服务项管理 新建服务
export const PMS_BASICSETTING_SERVICEITEM_ADD = 'PMS_BASICSETTING_SERVICEITEM_ADD';

// PMS酒店管理系统 基础设置 基础设置-服务项管理 编辑服务
export const PMS_BASICSETTING_SERVICEITEM_EDIT = 'PMS_BASICSETTING_SERVICEITEM_EDIT';

// PMS酒店管理系统 基础设置 基础设置-服务项管理 编辑库存
export const PMS_BASICSETTING_SERVICEITEM_INVENTORY = 'PMS_BASICSETTING_SERVICEITEM_INVENTORY';

// PMS酒店管理系统 基础设置 基础设置-服务项管理 启用/禁用
export const PMS_BASICSETTING_SERVICEITEM_ENABLED = 'PMS_BASICSETTING_SERVICEITEM_ENABLED';

// PMS酒店管理系统 基础设置 基础设置-服务项管理 删除
export const PMS_BASICSETTING_SERVICEITEM_DELETE = 'PMS_BASICSETTING_SERVICEITEM_DELETE';
