// 运营后台 家居 商品列表 查看列表 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_LIST = 'OPERPORT_JIAJU_PRODUCTLIST_LIST';

// 运营后台 家居 商品列表 添加商品 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_ADD = 'OPERPORT_JIAJU_PRODUCTLIST_ADD';

// 运营后台 家居 商品列表 编辑商品 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_EDIT = 'OPERPORT_JIAJU_PRODUCTLIST_EDIT';

// 运营后台 家居 商品列表 上架商品 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_PUBLISH = 'OPERPORT_JIAJU_PRODUCTLIST_PUBLISH';

// 运营后台 家居 商品列表 下架商品 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_UNPUBLISH = 'OPERPORT_JIAJU_PRODUCTLIST_UNPUBLISH';

// 运营后台 家居 商品列表 删除商品 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_DELETE = 'OPERPORT_JIAJU_PRODUCTLIST_DELETE';

// 运营后台 家居 商品列表 导出商品 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_EXPORT = 'OPERPORT_JIAJU_PRODUCTLIST_EXPORT';

// 运营后台 家居 商品列表 批量上架 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_BATCHPUBLISH = 'OPERPORT_JIAJU_PRODUCTLIST_BATCHPUBLISH';

// 运营后台 家居 商品列表 批量下架 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_BATCHUNPUBLISH = 'OPERPORT_JIAJU_PRODUCTLIST_BATCHUNPUBLISH';

// 运营后台 家居 商品列表 移至回收站 黎国坚
export const OPERPORT_JIAJU_PRODUCTLIST_RECOVER = 'OPERPORT_JIAJU_PRODUCTLIST_RECOVER';

// 运营后台 家居 待审核商品列表 查看列表 黎国坚
export const OPERPORT_JIAJU_TOAPPROVEPROLIST_LIST = 'OPERPORT_JIAJU_TOAPPROVEPROLIST_LIST';

// 运营后台 家居 待审核商品列表 审核 黎国坚
export const OPERPORT_JIAJU_TOAPPROVEPROLIST_APPROVE = 'OPERPORT_JIAJU_TOAPPROVEPROLIST_APPROVE';

// 运营后台 家居 待审核商品列表 批量审核 黎国坚
export const OPERPORT_JIAJU_TOAPPROVEPROLIST_BATCHAPPROVE = 'OPERPORT_JIAJU_TOAPPROVEPROLIST_BATCHAPPROVE';

// 运营后台 家居 审核不通过商品列表 查看列表 黎国坚
export const OPERPORT_JIAJU_UNAPPROVEDPROLIST_LIST = 'OPERPORT_JIAJU_UNAPPROVEDPROLIST_LIST';

// 运营后台 家居 审核不通过商品列表 编辑商品 黎国坚
export const OPERPORT_JIAJU_UNAPPROVEDPROLIST_EDIT = 'OPERPORT_JIAJU_UNAPPROVEDPROLIST_EDIT';

// 运营后台 家居 审核不通过商品列表 删除商品 黎国坚
export const OPERPORT_JIAJU_UNAPPROVEDPROLIST_DELETE = 'OPERPORT_JIAJU_UNAPPROVEDPROLIST_DELETE';

// 运营后台 家居 审核不通过商品列表 移至回收站 黎国坚
export const OPERPORT_JIAJU_UNAPPROVEDPROLIST_RECOVER = 'OPERPORT_JIAJU_UNAPPROVEDPROLIST_RECOVER';

// 运营后台 家居 商品分类管理 查看列表 黎国坚
export const OPERPORT_JIAJU_PROCATEGORYLIST_LIST = 'OPERPORT_JIAJU_PROCATEGORYLIST_LIST';

// 运营后台 家居 商品分类管理 添加一级分类 黎国坚
export const OPERPORT_JIAJU_PROCATEGORYLIST_ADDCAT = 'OPERPORT_JIAJU_PROCATEGORYLIST_ADDCAT';

// 运营后台 家居 商品分类管理 添加子分类 黎国坚
export const OPERPORT_JIAJU_PROCATEGORYLIST_ADDSUBCAT = 'OPERPORT_JIAJU_PROCATEGORYLIST_ADDSUBCAT';

// 运营后台 家居 商品分类管理 编辑 黎国坚
export const OPERPORT_JIAJU_PROCATEGORYLIST_EDIT = 'OPERPORT_JIAJU_PROCATEGORYLIST_EDIT';

// 运营后台 家居 商品分类管理 启用 黎国坚
export const OPERPORT_JIAJU_PROCATEGORYLIST_ENABLE = 'OPERPORT_JIAJU_PROCATEGORYLIST_ENABLE';

// 运营后台 家居 商品分类管理 禁用 黎国坚
export const OPERPORT_JIAJU_PROCATEGORYLIST_DISABLE = 'OPERPORT_JIAJU_PROCATEGORYLIST_DISABLE';

// 运营后台 家居 商品分类管理 删除 黎国坚
export const OPERPORT_JIAJU_PROCATEGORYLIST_DELETE = 'OPERPORT_JIAJU_PROCATEGORYLIST_DELETE';

// 运营后台 家居 商品分类管理 设置品牌 黎国坚
export const OPERPORT_JIAJU_PROCATEGORYLIST_SETBRAND = 'OPERPORT_JIAJU_PROCATEGORYLIST_SETBRAND';

// 运营后台 家居 品牌列表 查看列表 黎国坚
export const OPERPORT_JIAJU_BRANDLIST_LIST = 'OPERPORT_JIAJU_BRANDLIST_LIST';

// 运营后台 家居 品牌列表 编辑品牌 黎国坚
export const OPERPORT_JIAJU_BRANDLIST_EDIT = 'OPERPORT_JIAJU_BRANDLIST_EDIT';

// 运营后台 家居 品牌列表 删除品牌 黎国坚
export const OPERPORT_JIAJU_BRANDLIST_DELETE = 'OPERPORT_JIAJU_BRANDLIST_DELETE';

// 运营后台 家居 品牌列表 启用 黎国坚
export const OPERPORT_JIAJU_BRANDLIST_ENABLE = 'OPERPORT_JIAJU_BRANDLIST_ENABLE';

// 运营后台 家居 品牌列表 禁用 黎国坚
export const OPERPORT_JIAJU_BRANDLIST_DISABLE = 'OPERPORT_JIAJU_BRANDLIST_DISABLE';

// 运营后台 家居 品牌分类管理 查看列表 黎国坚
export const OPERPORT_JIAJU_BRANDCATEGORYLIST_LIST = 'OPERPORT_JIAJU_BRANDCATEGORYLIST_LIST';

// 运营后台 家居 品牌分类管理 添加一级分类 黎国坚
export const OPERPORT_JIAJU_BRANDCATEGORYLIST_ADDCAT = 'OPERPORT_JIAJU_BRANDCATEGORYLIST_ADDCAT';

// 运营后台 家居 品牌分类管理 添加子分类 黎国坚
export const OPERPORT_JIAJU_BRANDCATEGORYLIST_ADDSUBCAT = 'OPERPORT_JIAJU_BRANDCATEGORYLIST_ADDSUBCAT';

// 运营后台 家居 品牌分类管理 编辑 黎国坚
export const OPERPORT_JIAJU_BRANDCATEGORYLIST_EDIT = 'OPERPORT_JIAJU_BRANDCATEGORYLIST_EDIT';

// 运营后台 家居 品牌分类管理 删除 黎国坚
export const OPERPORT_JIAJU_BRANDCATEGORYLIST_DELETE = 'OPERPORT_JIAJU_BRANDCATEGORYLIST_DELETE';

// 运营后台 家居 商品回收站 查看列表 黎国坚
export const OPERPORT_JIAJU_PRORECYCLEBIN_LIST = 'OPERPORT_JIAJU_PRORECYCLEBIN_LIST';

// 运营后台 家居 商品回收站 还原 黎国坚
export const OPERPORT_JIAJU_PRORECYCLEBIN_RESTORE = 'OPERPORT_JIAJU_PRORECYCLEBIN_RESTORE';

// 运营后台 家居 商品回收站 删除 黎国坚
export const OPERPORT_JIAJU_PRORECYCLEBIN_DELETE = 'OPERPORT_JIAJU_PRORECYCLEBIN_DELETE';

// 运营后台 家居 商品回收站 批量还原 黎国坚
export const OPERPORT_JIAJU_PRORECYCLEBIN_BATCHRESTORE = 'OPERPORT_JIAJU_PRORECYCLEBIN_BATCHRESTORE';

// 运营后台 家居 商品回收站 批量删除 黎国坚
export const OPERPORT_JIAJU_PRORECYCLEBIN_BATCHDELETE = 'OPERPORT_JIAJU_PRORECYCLEBIN_BATCHDELETE';

// 运营后台 家居 商品评论 查看列表 黎国坚
export const OPERPORT_JIAJU_PROCOMMENTLIST_LIST = 'OPERPORT_JIAJU_PROCOMMENTLIST_LIST';

// 运营后台 家居 商品评论 审核 黎国坚
export const OPERPORT_JIAJU_PROCOMMENTLIST_APPROVE = 'OPERPORT_JIAJU_PROCOMMENTLIST_APPROVE';

// 运营后台 家居 商品评论 取消审核 黎国坚
export const OPERPORT_JIAJU_PROCOMMENTLIST_DEAPPROVE = 'OPERPORT_JIAJU_PROCOMMENTLIST_DEAPPROVE';

// 运营后台 家居 商品评论 回复 黎国坚
export const OPERPORT_JIAJU_PROCOMMENTLIST_REPLY = 'OPERPORT_JIAJU_PROCOMMENTLIST_REPLY';

// 运营后台 家居 商品评论 删除回复 黎国坚
export const OPERPORT_JIAJU_PROCOMMENTLIST_DELREPLY = 'OPERPORT_JIAJU_PROCOMMENTLIST_DELREPLY';

// 运营后台 家居 套餐管理 查看列表 黎国坚
export const OPERPORT_JIAJU_PACKAGELIST_LIST = 'OPERPORT_JIAJU_PACKAGELIST_LIST';

// 运营后台 家居 套餐管理 查看套餐 黎国坚
export const OPERPORT_JIAJU_PACKAGELIST_VIEW = 'OPERPORT_JIAJU_PACKAGELIST_VIEW';

// 运营后台 家居 套餐管理 添加套餐 黎国坚
export const OPERPORT_JIAJU_PACKAGELIST_ADD = 'OPERPORT_JIAJU_PACKAGELIST_ADD';

// 运营后台 家居 套餐管理 编辑套餐 黎国坚
export const OPERPORT_JIAJU_PACKAGELIST_EDIT = 'OPERPORT_JIAJU_PACKAGELIST_EDIT';

// 运营后台 家居 套餐管理 删除套餐 黎国坚
export const OPERPORT_JIAJU_PACKAGELIST_DELETE = 'OPERPORT_JIAJU_PACKAGELIST_DELETE';

// 运营后台 家居 套餐管理 上架套餐 黎国坚
export const OPERPORT_JIAJU_PACKAGELIST_PUBLISH = 'OPERPORT_JIAJU_PACKAGELIST_PUBLISH';

// 运营后台 家居 套餐管理 下架套餐 黎国坚
export const OPERPORT_JIAJU_PACKAGELIST_UNPUBLISH = 'OPERPORT_JIAJU_PACKAGELIST_UNPUBLISH';

// 运营后台 家居 套餐管理 置顶 黎国坚
export const OPERPORT_JIAJU_PACKAGELIST_TOP = 'OPERPORT_JIAJU_PACKAGELIST_TOP';

// 运营后台 家居 套餐管理 取消置顶 黎国坚
export const OPERPORT_JIAJU_PACKAGELIST_CANCELTOP = 'OPERPORT_JIAJU_PACKAGELIST_CANCELTOP';

// 运营后台 家居 套餐待审核列表 查看列表 黎国坚
export const OPERPORT_JIAJU_TOAPPRPACKLIST_LIST = 'OPERPORT_JIAJU_TOAPPRPACKLIST_LIST';

// 运营后台 家居 套餐待审核列表 查看套餐 黎国坚
export const OPERPORT_JIAJU_TOAPPRPACKLIST_VIEW = 'OPERPORT_JIAJU_TOAPPRPACKLIST_VIEW';

// 运营后台 家居 套餐待审核列表 审核 黎国坚
export const OPERPORT_JIAJU_TOAPPRPACKLIST_APPROVE = 'OPERPORT_JIAJU_TOAPPRPACKLIST_APPROVE';

// 运营后台 家居 套餐待审核列表 批量审核 黎国坚
export const OPERPORT_JIAJU_TOAPPRPACKLIST_BATCHAPPROVE = 'OPERPORT_JIAJU_TOAPPRPACKLIST_BATCHAPPROVE';

// 运营后台 家居 套餐审核不通过列表 查看列表 黎国坚
export const OPERPORT_JIAJU_UNAPPRPACKLIST_LIST = 'OPERPORT_JIAJU_UNAPPRPACKLIST_LIST';

// 运营后台 家居 套餐审核不通过列表 编辑 黎国坚
export const OPERPORT_JIAJU_UNAPPRPACKLIST_EDIT = 'OPERPORT_JIAJU_UNAPPRPACKLIST_EDIT';

// 运营后台 家居 套餐审核不通过列表 删除 黎国坚
export const OPERPORT_JIAJU_UNAPPRPACKLIST_DELETE = 'OPERPORT_JIAJU_UNAPPRPACKLIST_DELETE';

// 运营后台 家居 适用空间管理 查看列表 黎国坚
export const OPERPORT_JIAJU_SPACELIST_LIST = 'OPERPORT_JIAJU_SPACELIST_LIST';

// 运营后台 家居 适用空间管理 添加 黎国坚
export const OPERPORT_JIAJU_SPACELIST_ADD = 'OPERPORT_JIAJU_SPACELIST_ADD';

// 运营后台 家居 适用空间管理 编辑 黎国坚
export const OPERPORT_JIAJU_SPACELIST_EDIT = 'OPERPORT_JIAJU_SPACELIST_EDIT';

// 运营后台 家居 适用空间管理 启用 黎国坚
export const OPERPORT_JIAJU_SPACELIST_ENABLE = 'OPERPORT_JIAJU_SPACELIST_ENABLE';

// 运营后台 家居 适用空间管理 禁用 黎国坚
export const OPERPORT_JIAJU_SPACELIST_DISABLE = 'OPERPORT_JIAJU_SPACELIST_DISABLE';

// 运营后台 家居 适用空间管理 删除 黎国坚
export const OPERPORT_JIAJU_SPACELIST_DELETE = 'OPERPORT_JIAJU_SPACELIST_DELETE';

// 运营后台 家居 适用空间管理 关联分类 黎国坚
export const OPERPORT_JIAJU_SPACELIST_SETCATEGORY = 'OPERPORT_JIAJU_SPACELIST_SETCATEGORY';

// 运营后台 家居 规格属性管理-基本属性组 查看列表 黎国坚
export const OPERPORT_JIAJU_BASICPROPERTYLIST_LIST = 'OPERPORT_JIAJU_BASICPROPERTYLIST_LIST';

// 运营后台 家居 规格属性管理-基本属性组 添加属性 黎国坚
export const OPERPORT_JIAJU_BASICPROPERTYLIST_ADD = 'OPERPORT_JIAJU_BASICPROPERTYLIST_ADD';

// 运营后台 家居 规格属性管理-基本属性组 导入属性 黎国坚
export const OPERPORT_JIAJU_BASICPROPERTYLIST_IMPORT = 'OPERPORT_JIAJU_BASICPROPERTYLIST_IMPORT';

// 运营后台 家居 规格属性管理-基本属性组 编辑属性 黎国坚
export const OPERPORT_JIAJU_BASICPROPERTYLIST_EDIT = 'OPERPORT_JIAJU_BASICPROPERTYLIST_EDIT';

// 运营后台 家居 规格属性管理-基本属性组 删除属性 黎国坚
export const OPERPORT_JIAJU_BASICPROPERTYLIST_DELETE = 'OPERPORT_JIAJU_BASICPROPERTYLIST_DELETE';

// 运营后台 家居 规格属性管理-基本属性组 管理标准值 黎国坚
export const OPERPORT_JIAJU_BASICPROPERTYLIST_SETPROPERTY = 'OPERPORT_JIAJU_BASICPROPERTYLIST_SETPROPERTY';

// 运营后台 家居 规格属性管理-规格属性组 查看列表 黎国坚
export const OPERPORT_JIAJU_SALESPROPERTYLIST_LIST = 'OPERPORT_JIAJU_SALESPROPERTYLIST_LIST';

// 运营后台 家居 规格属性管理-规格属性组 添加属性 黎国坚
export const OPERPORT_JIAJU_SALESPROPERTYLIST_ADD = 'OPERPORT_JIAJU_SALESPROPERTYLIST_ADD';

// 运营后台 家居 规格属性管理-规格属性组 导入属性 黎国坚
export const OPERPORT_JIAJU_SALESPROPERTYLIST_IMPORT = 'OPERPORT_JIAJU_SALESPROPERTYLIST_IMPORT';

// 运营后台 家居 规格属性管理-规格属性组 编辑属性 黎国坚
export const OPERPORT_JIAJU_SALESPROPERTYLIST_EDIT = 'OPERPORT_JIAJU_SALESPROPERTYLIST_EDIT';

// 运营后台 家居 规格属性管理-规格属性组 删除属性 黎国坚
export const OPERPORT_JIAJU_SALESPROPERTYLIST_DELETE = 'OPERPORT_JIAJU_SALESPROPERTYLIST_DELETE';

// 运营后台 家居 规格属性管理-规格属性组 管理标准值 黎国坚
export const OPERPORT_JIAJU_SALESPROPERTYLIST_SETPROPERTY = 'OPERPORT_JIAJU_SALESPROPERTYLIST_SETPROPERTY';

// 运营后台 家居 资讯列表 查看列表 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_LIST = 'OPERPORT_JIAJU_ARTICLELIST_LIST';

// 运营后台 家居 资讯列表 添加资讯 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_ADD = 'OPERPORT_JIAJU_ARTICLELIST_ADD';

// 运营后台 家居 资讯列表 编辑资讯 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_EDIT = 'OPERPORT_JIAJU_ARTICLELIST_EDIT';

// 运营后台 家居 资讯列表 查看资讯 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_VIEW = 'OPERPORT_JIAJU_ARTICLELIST_VIEW';

// 运营后台 家居 资讯列表 预览 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_PREVIEW = 'OPERPORT_JIAJU_ARTICLELIST_PREVIEW';

// 运营后台 家居 资讯列表 发布 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_PUBLISH = 'OPERPORT_JIAJU_ARTICLELIST_PUBLISH';

// 运营后台 家居 资讯列表 取消发布 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_UNPUBLISH = 'OPERPORT_JIAJU_ARTICLELIST_UNPUBLISH';

// 运营后台 家居 资讯列表 修改项目 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_SETPROJECT = 'OPERPORT_JIAJU_ARTICLELIST_SETPROJECT';

// 运营后台 家居 资讯列表 设为精华 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_TOP = 'OPERPORT_JIAJU_ARTICLELIST_TOP';

// 运营后台 家居 资讯列表 取消精华 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_CANCELTOP = 'OPERPORT_JIAJU_ARTICLELIST_CANCELTOP';

// 运营后台 家居 资讯列表 删除 黎国坚
export const OPERPORT_JIAJU_ARTICLELIST_DELETE = 'OPERPORT_JIAJU_ARTICLELIST_DELETE';

// 运营后台 家居 资讯评论列表 查看列表 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_LIST = 'OPERPORT_JIAJU_ARTCOMMENTLIST_LIST';

// 运营后台 家居 资讯评论列表 审核 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_APPROVE = 'OPERPORT_JIAJU_ARTCOMMENTLIST_APPROVE';

// 运营后台 家居 资讯评论列表 取消审核 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_DEAPPROVE = 'OPERPORT_JIAJU_ARTCOMMENTLIST_DEAPPROVE';

// 运营后台 家居 资讯评论列表 回复 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_REPLY = 'OPERPORT_JIAJU_ARTCOMMENTLIST_REPLY';

// 运营后台 家居 资讯评论列表 删除回复 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_DELREPLY = 'OPERPORT_JIAJU_ARTCOMMENTLIST_DELREPLY';

// 运营后台 家居 资讯评论列表 设为精华 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_TOP = 'OPERPORT_JIAJU_ARTCOMMENTLIST_TOP';

// 运营后台 家居 资讯评论列表 取消精华 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_CANCELTOP = 'OPERPORT_JIAJU_ARTCOMMENTLIST_CANCELTOP';

// 运营后台 家居 资讯评论列表 批量审核 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_BATCHAPPROVE = 'OPERPORT_JIAJU_ARTCOMMENTLIST_BATCHAPPROVE';

// 运营后台 家居 资讯评论列表 批量取消审核 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_BATCHDEAPPROVE = 'OPERPORT_JIAJU_ARTCOMMENTLIST_BATCHDEAPPROVE';

// 运营后台 家居 资讯评论列表 批量设为精华 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_BATCHTOP = 'OPERPORT_JIAJU_ARTCOMMENTLIST_BATCHTOP';

// 运营后台 家居 资讯评论列表 批量取消精华 黎国坚
export const OPERPORT_JIAJU_ARTCOMMENTLIST_BATCHCANCELTOP = 'OPERPORT_JIAJU_ARTCOMMENTLIST_BATCHCANCELTOP';

// 运营后台 家居 资讯分类管理 查看列表 黎国坚
export const OPERPORT_JIAJU_ARTCATEGORYLIST_LIST = 'OPERPORT_JIAJU_ARTCATEGORYLIST_LIST';

// 运营后台 家居 资讯分类管理 添加一级分类 黎国坚
export const OPERPORT_JIAJU_ARTCATEGORYLIST_ADDCAT = 'OPERPORT_JIAJU_ARTCATEGORYLIST_ADDCAT';

// 运营后台 家居 资讯分类管理 添加子分类 黎国坚
export const OPERPORT_JIAJU_ARTCATEGORYLIST_ADDSUBCAT = 'OPERPORT_JIAJU_ARTCATEGORYLIST_ADDSUBCAT';

// 运营后台 家居 资讯分类管理 编辑 黎国坚
export const OPERPORT_JIAJU_ARTCATEGORYLIST_EDIT = 'OPERPORT_JIAJU_ARTCATEGORYLIST_EDIT';

// 运营后台 家居 资讯分类管理 删除 黎国坚
export const OPERPORT_JIAJU_ARTCATEGORYLIST_DELETE = 'OPERPORT_JIAJU_ARTCATEGORYLIST_DELETE';

// 运营后台 家居 晒家列表 查看列表 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_LIST = 'OPERPORT_JIAJU_SHOWHOMELIST_LIST';

// 运营后台 家居 晒家列表 添加晒家 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_ADD = 'OPERPORT_JIAJU_SHOWHOMELIST_ADD';

// 运营后台 家居 晒家列表 编辑晒家 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_EDIT = 'OPERPORT_JIAJU_SHOWHOMELIST_EDIT';

// 运营后台 家居 晒家列表 查看晒家 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_VIEW = 'OPERPORT_JIAJU_SHOWHOMELIST_VIEW';

// 运营后台 家居 晒家列表 预览 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_PREVIEW = 'OPERPORT_JIAJU_SHOWHOMELIST_PREVIEW';

// 运营后台 家居 晒家列表 发布 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_PUBLISH = 'OPERPORT_JIAJU_SHOWHOMELIST_PUBLISH';

// 运营后台 家居 晒家列表 取消发布 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_UNPUBLISH = 'OPERPORT_JIAJU_SHOWHOMELIST_UNPUBLISH';

// 运营后台 家居 晒家列表 修改项目 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_SETPROJECT = 'OPERPORT_JIAJU_SHOWHOMELIST_SETPROJECT';

// 运营后台 家居 晒家列表 设为精华 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_TOP = 'OPERPORT_JIAJU_SHOWHOMELIST_TOP';

// 运营后台 家居 晒家列表 取消精华 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_CANCELTOP = 'OPERPORT_JIAJU_SHOWHOMELIST_CANCELTOP';

// 运营后台 家居 晒家列表 删除 黎国坚
export const OPERPORT_JIAJU_SHOWHOMELIST_DELETE = 'OPERPORT_JIAJU_SHOWHOMELIST_DELETE';

// 运营后台 家居 晒家评论列表 查看列表 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_LIST = 'OPERPORT_JIAJU_SHCOMMENTLIST_LIST';

// 运营后台 家居 晒家评论列表 审核 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_APPROVE = 'OPERPORT_JIAJU_SHCOMMENTLIST_APPROVE';

// 运营后台 家居 晒家评论列表 取消审核 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_DEAPPROVE = 'OPERPORT_JIAJU_SHCOMMENTLIST_DEAPPROVE';

// 运营后台 家居 晒家评论列表 回复 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_REPLY = 'OPERPORT_JIAJU_SHCOMMENTLIST_REPLY';

// 运营后台 家居 晒家评论列表 删除回复 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_DELREPLY = 'OPERPORT_JIAJU_SHCOMMENTLIST_DELREPLY';

// 运营后台 家居 晒家评论列表 设为精华 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_TOP = 'OPERPORT_JIAJU_SHCOMMENTLIST_TOP';

// 运营后台 家居 晒家评论列表 取消精华 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_CANCELTOP = 'OPERPORT_JIAJU_SHCOMMENTLIST_CANCELTOP';

// 运营后台 家居 晒家评论列表 批量审核 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_BATCHAPPROVE = 'OPERPORT_JIAJU_SHCOMMENTLIST_BATCHAPPROVE';

// 运营后台 家居 晒家评论列表 批量取消审核 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_BATCHDEAPPROVE = 'OPERPORT_JIAJU_SHCOMMENTLIST_BATCHDEAPPROVE';

// 运营后台 家居 晒家评论列表 批量设为精华 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_BATCHTOP = 'OPERPORT_JIAJU_SHCOMMENTLIST_BATCHTOP';

// 运营后台 家居 晒家评论列表 批量取消精华 黎国坚
export const OPERPORT_JIAJU_SHCOMMENTLIST_BATCHCANCELTOP = 'OPERPORT_JIAJU_SHCOMMENTLIST_BATCHCANCELTOP';

// 运营后台 家居 页面列表 查看列表 黎国坚
export const OPERPORT_JIAJU_PAGELIST_LIST = 'OPERPORT_JIAJU_PAGELIST_LIST';

// 运营后台 家居 页面列表 编辑 黎国坚
export const OPERPORT_JIAJU_PAGELIST_EDIT = 'OPERPORT_JIAJU_PAGELIST_EDIT';

// 运营后台 家居 广告位管理 查看列表 黎国坚
export const OPERPORT_JIAJU_BANNERPOSITIONLIST_LIST = 'OPERPORT_JIAJU_BANNERPOSITIONLIST_LIST';

// 运营后台 家居 广告位管理 添加 黎国坚
export const OPERPORT_JIAJU_BANNERPOSITIONLIST_ADD = 'OPERPORT_JIAJU_BANNERPOSITIONLIST_ADD';

// 运营后台 家居 广告位管理 编辑 黎国坚
export const OPERPORT_JIAJU_BANNERPOSITIONLIST_EDIT = 'OPERPORT_JIAJU_BANNERPOSITIONLIST_EDIT';

// 运营后台 家居 广告项管理 查看列表 黎国坚
export const OPERPORT_JIAJU_BANNERLIST_LIST = 'OPERPORT_JIAJU_BANNERLIST_LIST';

// 运营后台 家居 广告项管理 添加 黎国坚
export const OPERPORT_JIAJU_BANNERLIST_ADD = 'OPERPORT_JIAJU_BANNERLIST_ADD';

// 运营后台 家居 广告项管理 编辑 黎国坚
export const OPERPORT_JIAJU_BANNERLIST_EDIT = 'OPERPORT_JIAJU_BANNERLIST_EDIT';

// 运营后台 家居 广告项管理 启用 黎国坚
export const OPERPORT_JIAJU_BANNERLIST_ENABLE = 'OPERPORT_JIAJU_BANNERLIST_ENABLE';

// 运营后台 家居 广告项管理 禁用 黎国坚
export const OPERPORT_JIAJU_BANNERLIST_DISABLE = 'OPERPORT_JIAJU_BANNERLIST_DISABLE';

// 运营后台 家居 广告项管理 删除 黎国坚
export const OPERPORT_JIAJU_BANNERLIST_DELETE = 'OPERPORT_JIAJU_BANNERLIST_DELETE';

// 运营后台 家居 支付记录列表 查看列表 黎国坚
export const OPERPORT_JIAJU_PAYRECORDLIST_LIST = 'OPERPORT_JIAJU_PAYRECORDLIST_LIST';

// 运营后台 家居 支付记录列表 修改 黎国坚
export const OPERPORT_JIAJU_PAYRECORDLIST_EDIT = 'OPERPORT_JIAJU_PAYRECORDLIST_EDIT';

// 运营后台 家居 支付记录列表 查看日志 黎国坚
export const OPERPORT_JIAJU_PAYRECORDLIST_VIEWLOG = 'OPERPORT_JIAJU_PAYRECORDLIST_VIEWLOG';

// 运营后台 家居 支付记录列表 导出 黎国坚
export const OPERPORT_JIAJU_PAYRECORDLIST_EXPORT = 'OPERPORT_JIAJU_PAYRECORDLIST_EXPORT';

// 运营后台 家居 支付方式配置列表 查看列表 黎国坚
export const OPERPORT_JIAJU_PAYTYPELIST_LIST = 'OPERPORT_JIAJU_PAYTYPELIST_LIST';

// 运营后台 家居 支付方式配置列表 启用 黎国坚
export const OPERPORT_JIAJU_PAYTYPELIST_ENABLE = 'OPERPORT_JIAJU_PAYTYPELIST_ENABLE';

// 运营后台 家居 支付方式配置列表 禁用 黎国坚
export const OPERPORT_JIAJU_PAYTYPELIST_DISABLE = 'OPERPORT_JIAJU_PAYTYPELIST_DISABLE';

// 运营后台 家居 预存款管理-列表 查看列表 黎国坚
export const OPERPORT_JIAJU_PREDEPOSITLIST_LIST = 'OPERPORT_JIAJU_PREDEPOSITLIST_LIST';

// 运营后台 家居 预存款管理-列表 设置有效期 黎国坚
export const OPERPORT_JIAJU_PREDEPOSITLIST_SETTERM = 'OPERPORT_JIAJU_PREDEPOSITLIST_SETTERM';

// 运营后台 家居 预存款管理-列表 充值预存款 黎国坚
export const OPERPORT_JIAJU_PREDEPOSITLIST_RECHARGE = 'OPERPORT_JIAJU_PREDEPOSITLIST_RECHARGE';

// 运营后台 家居 预存款管理-列表 导出预存款 黎国坚
export const OPERPORT_JIAJU_PREDEPOSITLIST_EXPORT = 'OPERPORT_JIAJU_PREDEPOSITLIST_EXPORT';

// 运营后台 家居 预存款管理-交易明细 查看列表 黎国坚
export const OPERPORT_JIAJU_PREDEPOSITTRADELIST_LIST = 'OPERPORT_JIAJU_PREDEPOSITTRADELIST_LIST';

// 运营后台 家居 预存款管理-交易明细 导出 黎国坚
export const OPERPORT_JIAJU_PREDEPOSITTRADELIST_EXPORT = 'OPERPORT_JIAJU_PREDEPOSITTRADELIST_EXPORT';

// 运营后台 家居 预存款管理-操作日志 查看列表 黎国坚
export const OPERPORT_JIAJU_PREDEPOSITLOG_LIST = 'OPERPORT_JIAJU_PREDEPOSITLOG_LIST';

// 运营后台 家居 钱包管理-列表 查看列表 黎国坚
export const OPERPORT_JIAJU_WALLETLIST_LIST = 'OPERPORT_JIAJU_WALLETLIST_LIST';

// 运营后台 家居 钱包管理-列表 充值 黎国坚
export const OPERPORT_JIAJU_WALLETLIST_RECHARGE = 'OPERPORT_JIAJU_WALLETLIST_RECHARGE';

// 运营后台 家居 钱包管理-列表 导出 黎国坚
export const OPERPORT_JIAJU_WALLETLIST_EXPORT = 'OPERPORT_JIAJU_WALLETLIST_EXPORT';

// 运营后台 家居 钱包管理-交易明细 查看列表 黎国坚
export const OPERPORT_JIAJU_WALLETTRADELIST_LIST = 'OPERPORT_JIAJU_WALLETTRADELIST_LIST';

// 运营后台 家居 钱包管理-交易明细 导出 黎国坚
export const OPERPORT_JIAJU_WALLETTRADELIST_EXPORT = 'OPERPORT_JIAJU_WALLETTRADELIST_EXPORT';

// 运营后台 家居 促销规则列表 查看列表 黎国坚
export const OPERPORT_JIAJU_PROMOTIONLIST_LIST = 'OPERPORT_JIAJU_PROMOTIONLIST_LIST';

// 运营后台 家居 促销规则列表 添加 黎国坚
export const OPERPORT_JIAJU_PROMOTIONLIST_ADD = 'OPERPORT_JIAJU_PROMOTIONLIST_ADD';

// 运营后台 家居 促销规则列表 编辑 黎国坚
export const OPERPORT_JIAJU_PROMOTIONLIST_EDIT = 'OPERPORT_JIAJU_PROMOTIONLIST_EDIT';

// 运营后台 家居 促销规则列表 查看 黎国坚
export const OPERPORT_JIAJU_PROMOTIONLIST_VIEW = 'OPERPORT_JIAJU_PROMOTIONLIST_VIEW';

// 运营后台 家居 促销规则列表 删除 黎国坚
export const OPERPORT_JIAJU_PROMOTIONLIST_DELETE = 'OPERPORT_JIAJU_PROMOTIONLIST_DELETE';

// 运营后台 家居 促销规则列表 启用 黎国坚
export const OPERPORT_JIAJU_PROMOTIONLIST_ENABLE = 'OPERPORT_JIAJU_PROMOTIONLIST_ENABLE';

// 运营后台 家居 促销规则列表 禁用 黎国坚
export const OPERPORT_JIAJU_PROMOTIONLIST_DISABLE = 'OPERPORT_JIAJU_PROMOTIONLIST_DISABLE';

// 运营后台 家居 优惠券列表 查看列表 黎国坚
export const OPERPORT_JIAJU_COUPONLIST_LIST = 'OPERPORT_JIAJU_COUPONLIST_LIST';

// 运营后台 家居 优惠券列表 添加 黎国坚
export const OPERPORT_JIAJU_COUPONLIST_ADD = 'OPERPORT_JIAJU_COUPONLIST_ADD';

// 运营后台 家居 优惠券列表 编辑 黎国坚
export const OPERPORT_JIAJU_COUPONLIST_EDIT = 'OPERPORT_JIAJU_COUPONLIST_EDIT';

// 运营后台 家居 优惠券列表 查看 黎国坚
export const OPERPORT_JIAJU_COUPONLIST_VIEW = 'OPERPORT_JIAJU_COUPONLIST_VIEW';

// 运营后台 家居 优惠券列表 删除 黎国坚
export const OPERPORT_JIAJU_COUPONLIST_DELETE = 'OPERPORT_JIAJU_COUPONLIST_DELETE';

// 运营后台 家居 优惠券列表 启用 黎国坚
export const OPERPORT_JIAJU_COUPONLIST_ENABLE = 'OPERPORT_JIAJU_COUPONLIST_ENABLE';

// 运营后台 家居 优惠券列表 禁用 黎国坚
export const OPERPORT_JIAJU_COUPONLIST_DISABLE = 'OPERPORT_JIAJU_COUPONLIST_DISABLE';

// 运营后台 家居 优惠券列表 批量派发 黎国坚
export const OPERPORT_JIAJU_COUPONLIST_BATCHDISTRIBUTE = 'OPERPORT_JIAJU_COUPONLIST_BATCHDISTRIBUTE';

// 运营后台 家居 售后申请列表 查看列表 曾小龙
export const OPERPORT_JIAJU_AFTERSERVICELIST_LIST = 'OPERPORT_JIAJU_AFTERSERVICELIST_LIST';

// 运营后台 家居 售后申请列表 详情 曾小龙
export const OPERPORT_JIAJU_AFTERSERVICELIST_DETAILS = 'OPERPORT_JIAJU_AFTERSERVICELIST_DETAILS';

// 运营后台 家居 售后申请列表 编辑 曾小龙
export const OPERPORT_JIAJU_AFTERSERVICELIST_EDIT = 'OPERPORT_JIAJU_AFTERSERVICELIST_EDIT';

// 运营后台 家居 售后申请列表 审核 曾小龙
export const OPERPORT_JIAJU_AFTERSERVICELIST_CHECK = 'OPERPORT_JIAJU_AFTERSERVICELIST_CHECK';

// 运营后台 家居 售后申请列表 新增售后申请单 曾小龙
export const OPERPORT_JIAJU_AFTERSERVICELIST_ADD = 'OPERPORT_JIAJU_AFTERSERVICELIST_ADD';

// 运营后台 家居 售后申请列表 关闭售后申请单 曾小龙
export const OPERPORT_JIAJU_AFTERSERVICELIST_CLOSE = 'OPERPORT_JIAJU_AFTERSERVICELIST_CLOSE';

// 运营后台 家居 退货单管理 查看列表 曾小龙
export const OPERPORT_JIAJU_RETURNSLIST_LIST = 'OPERPORT_JIAJU_RETURNSLIST_LIST';

// 运营后台 家居 退货单管理 详情 曾小龙
export const OPERPORT_JIAJU_RETURNSLIST_DETAILS = 'OPERPORT_JIAJU_RETURNSLIST_DETAILS';

// 运营后台 家居 退货单管理 确认签收 曾小龙
export const OPERPORT_JIAJU_RETURNSLIST_SIGNIN = 'OPERPORT_JIAJU_RETURNSLIST_SIGNIN';

// 运营后台 家居 退货单管理 导出退货单 曾小龙
export const OPERPORT_JIAJU_RETURNSLIST_EXPORTREPORT = 'OPERPORT_JIAJU_RETURNSLIST_EXPORTREPORT';

// 运营后台 家居 换货单管理 查看列表 曾小龙
export const OPERPORT_JIAJU_EXCHANGELIST_LIST = 'OPERPORT_JIAJU_EXCHANGELIST_LIST';

// 运营后台 家居 换货单管理 详情 曾小龙
export const OPERPORT_JIAJU_EXCHANGELIST_DETAILS = 'OPERPORT_JIAJU_EXCHANGELIST_DETAILS';

// 运营后台 家居 换货单管理 新增换货订单 曾小龙
export const OPERPORT_JIAJU_EXCHANGELIST_ADDNEW = 'OPERPORT_JIAJU_EXCHANGELIST_ADDNEW';

// 运营后台 家居 换货单管理 导出换货单 曾小龙
export const OPERPORT_JIAJU_EXCHANGELIST_EXPORTREPORT = 'OPERPORT_JIAJU_EXCHANGELIST_EXPORTREPORT';

// 运营后台 家居 退款单管理 查看列表 曾小龙
export const OPERPORT_JIAJU_REFUNDLIST_LIST = 'OPERPORT_JIAJU_REFUNDLIST_LIST';

// 运营后台 家居 退款单管理 详情 曾小龙
export const OPERPORT_JIAJU_REFUNDLIST_DETAILS = 'OPERPORT_JIAJU_REFUNDLIST_DETAILS';

// 运营后台 家居 退款单管理 执行退款 曾小龙
export const OPERPORT_JIAJU_REFUNDLIST_REFUND = 'OPERPORT_JIAJU_REFUNDLIST_REFUND';

// 运营后台 家居 退款单管理 同意退款 曾小龙
export const OPERPORT_JIAJU_REFUNDLIST_AGREE = 'OPERPORT_JIAJU_REFUNDLIST_AGREE';

// 运营后台 家居 退款单管理 取消退款单 曾小龙
export const OPERPORT_JIAJU_REFUNDLIST_CANCEL = 'OPERPORT_JIAJU_REFUNDLIST_CANCEL';

// 运营后台 家居 退款单管理 关闭售后申请单 曾小龙
export const OPERPORT_JIAJU_REFUNDLIST_CLOSE = 'OPERPORT_JIAJU_REFUNDLIST_CLOSE';

// 运营后台 家居 退款单管理 导出退款单 曾小龙
export const OPERPORT_JIAJU_REFUNDLIST_EXPORTREPORT = 'OPERPORT_JIAJU_REFUNDLIST_EXPORTREPORT';

// 运营后台 家居 支付记录列表 查看列表 曾小龙
export const OPERPORT_JIAJU_PAYMENTHISTORYLIST_LIST = 'OPERPORT_JIAJU_PAYMENTHISTORYLIST_LIST';

// 运营后台 家居 支付记录列表 导出 曾小龙
export const OPERPORT_JIAJU_PAYMENTHISTORYLIST_EXPORTREPORT = 'OPERPORT_JIAJU_PAYMENTHISTORYLIST_EXPORTREPORT';

// 运营后台 家居 支付记录列表 修改 曾小龙
export const OPERPORT_JIAJU_PAYMENTHISTORYLIST_AMEND = 'OPERPORT_JIAJU_PAYMENTHISTORYLIST_AMEND';

// 运营后台 家居 支付记录列表 日志 曾小龙
export const OPERPORT_JIAJU_PAYMENTHISTORYLIST_LOG = 'OPERPORT_JIAJU_PAYMENTHISTORYLIST_LOG';

// 运营后台 家居 支付方式配置列表 查看列表 曾小龙
export const OPERPORT_JIAJU_PAYMENTALLOCATION_LIST = 'OPERPORT_JIAJU_PAYMENTALLOCATION_LIST';

// 运营后台 家居 支付方式配置列表 编辑 曾小龙
export const OPERPORT_JIAJU_PAYMENTALLOCATION_EDIT = 'OPERPORT_JIAJU_PAYMENTALLOCATION_EDIT';

// 运营后台 家居 支付方式配置列表 启用/禁用 曾小龙
export const OPERPORT_JIAJU_PAYMENTALLOCATION_ACTIVATE = 'OPERPORT_JIAJU_PAYMENTALLOCATION_ACTIVATE';

// 运营后台 家居 预存款管理列表 查看列表 曾小龙
export const OPERPORT_JIAJU_PREDEPOSIT_LIST = 'OPERPORT_JIAJU_PREDEPOSIT_LIST';

// 运营后台 家居 预存款管理列表 设置有效期 曾小龙
export const OPERPORT_JIAJU_PREDEPOSIT_SET = 'OPERPORT_JIAJU_PREDEPOSIT_SET';

// 运营后台 家居 预存款管理列表 充值预存款 曾小龙
export const OPERPORT_JIAJU_PREDEPOSIT_PAY = 'OPERPORT_JIAJU_PREDEPOSIT_PAY';

// 运营后台 家居 预存款管理列表 +充值预存款 曾小龙
export const OPERPORT_JIAJU_PREDEPOSIT_PREPAID = 'OPERPORT_JIAJU_PREDEPOSIT_PREPAID';

// 运营后台 家居 预存款管理列表 导出预存款 曾小龙
export const OPERPORT_JIAJU_PREDEPOSIT_EXPORTREPORT = 'OPERPORT_JIAJU_PREDEPOSIT_EXPORTREPORT';

// 运营后台 家居 钱包管理 查看列表 曾小龙
export const OPERPORT_JIAJU_WALLET_LIST = 'OPERPORT_JIAJU_WALLET_LIST';

// 运营后台 家居 钱包管理 充值 曾小龙
export const OPERPORT_JIAJU_WALLET_PAY = 'OPERPORT_JIAJU_WALLET_PAY';

// 运营后台 家居 钱包管理 +充值钱包 曾小龙
export const OPERPORT_JIAJU_WALLET_PREPAID = 'OPERPORT_JIAJU_WALLET_PREPAID';

// 运营后台 家居 钱包管理 导出钱包 曾小龙
export const OPERPORT_JIAJU_WALLET_EXPORTREPORT = 'OPERPORT_JIAJU_WALLET_EXPORTREPORT';

// 运营后台 家居 支付退款日志 查看列表 曾小龙
export const OPERPORT_JIAJU_REFUNDLOG_LIST = 'OPERPORT_JIAJU_REFUNDLOG_LIST';

// 运营后台 家居 支付退款日志 详情 曾小龙
export const OPERPORT_JIAJU_REFUNDLOG_DETAILS = 'OPERPORT_JIAJU_REFUNDLOG_DETAILS';

// 运营后台 家居 短信推送任务 查看列表 曾小龙
export const OPERPORT_JIAJU_SMSPUSH_LIST = 'OPERPORT_JIAJU_SMSPUSH_LIST';

// 运营后台 家居 短信推送任务 全部重发 曾小龙
export const OPERPORT_JIAJU_SMSPUSH_ALLRETRY = 'OPERPORT_JIAJU_SMSPUSH_ALLRETRY';

// 运营后台 家居 短信推送任务 创建短信推送任务 曾小龙
export const OPERPORT_JIAJU_SMSPUSH_CREATE = 'OPERPORT_JIAJU_SMSPUSH_CREATE';

// 运营后台 家居 系统短信记录 查看列表 曾小龙
export const OPERPORT_JIAJU_SMSLIST_LIST = 'OPERPORT_JIAJU_SMSLIST_LIST';

// 运营后台 家居 家居系统全局配置 保存 曾小龙
export const OPERPORT_JIAJU_WHOLEALLOCATION_SAVE = 'OPERPORT_JIAJU_WHOLEALLOCATION_SAVE';

// 运营后台 家居 图片库 上传图片 曾小龙
export const OPERPORT_JIAJU_PICTUREGALLERY_UPLOAD = 'OPERPORT_JIAJU_PICTUREGALLERY_UPLOAD';

// 运营后台 家居 图片库 删除 曾小龙
export const OPERPORT_JIAJU_PICTUREGALLERY_DELETE = 'OPERPORT_JIAJU_PICTUREGALLERY_DELETE';

// 运营后台 家居 图片库 移动到 曾小龙
export const OPERPORT_JIAJU_PICTUREGALLERY_MOVE = 'OPERPORT_JIAJU_PICTUREGALLERY_MOVE';

// 运营后台 家居 图片库 重命名 曾小龙
export const OPERPORT_JIAJU_PICTUREGALLERY_RENAME = 'OPERPORT_JIAJU_PICTUREGALLERY_RENAME';

// 运营后台 家居 图片库 查看列表 曾小龙
export const OPERPORT_JIAJU_PICTUREGALLERY_LIST = 'OPERPORT_JIAJU_PICTUREGALLERY_LIST';

// 运营后台 家居 图片库 新增文件夹 曾小龙
export const OPERPORT_JIAJU_PICTUREGALLERY_ADD = 'OPERPORT_JIAJU_PICTUREGALLERY_ADD';

// 运营后台 家居 商家管理 查看列表 梅永坚
export const OPERPORT_JIAJU_SHOP_LIST = 'OPERPORT_JIAJU_SHOP_LIST';

// 运营后台 家居 商家管理 新增商家 梅永坚
export const OPERPORT_JIAJU_SHOP_ADD = 'OPERPORT_JIAJU_SHOP_ADD';

// 运营后台 家居 商家管理 批量上架 梅永坚
export const OPERPORT_JIAJU_SHOP_BATCHUPDATE = 'OPERPORT_JIAJU_SHOP_BATCHUPDATE';

// 运营后台 家居 商家管理 批量下架 梅永坚
export const OPERPORT_JIAJU_SHOP_BATCHFROMSALE = 'OPERPORT_JIAJU_SHOP_BATCHFROMSALE';

// 运营后台 家居 商家管理 批量冻结 梅永坚
export const OPERPORT_JIAJU_SHOP_BATCHFREEZE = 'OPERPORT_JIAJU_SHOP_BATCHFREEZE';

// 运营后台 家居 商家管理 导出查询结果 梅永坚
export const OPERPORT_JIAJU_SHOP_EXPORT = 'OPERPORT_JIAJU_SHOP_EXPORT';

// 运营后台 家居 商家管理 查看详情 梅永坚
export const OPERPORT_JIAJU_SHOP_DETAILS = 'OPERPORT_JIAJU_SHOP_DETAILS';

// 运营后台 家居 商家管理 编辑信息 梅永坚
export const OPERPORT_JIAJU_SHOP_EDIT = 'OPERPORT_JIAJU_SHOP_EDIT';

// 运营后台 家居 商家管理 上架 梅永坚
export const OPERPORT_JIAJU_SHOP_UPDATE = 'OPERPORT_JIAJU_SHOP_UPDATE';

// 运营后台 家居 商家管理 下架 梅永坚
export const OPERPORT_JIAJU_SHOP_FROMSALE = 'OPERPORT_JIAJU_SHOP_FROMSALE';

// 运营后台 家居 商家管理 冻结 梅永坚
export const OPERPORT_JIAJU_SHOP_FREEZE = 'OPERPORT_JIAJU_SHOP_FREEZE';

// 运营后台 家居 商家管理 解冻 梅永坚
export const OPERPORT_JIAJU_SHOP_UNFREEZE = 'OPERPORT_JIAJU_SHOP_UNFREEZE';

// 运营后台 家居 商家管理 关联厂商 梅永坚
export const OPERPORT_JIAJU_SHOP_ASSOCIATE = 'OPERPORT_JIAJU_SHOP_ASSOCIATE';

// 运营后台 家居 商家管理 解除关联 梅永坚
export const OPERPORT_JIAJU_SHOP_UNASSOCIATE = 'OPERPORT_JIAJU_SHOP_UNASSOCIATE';

// 运营后台 家居 商家管理 商家后台 梅永坚
export const OPERPORT_JIAJU_SHOP_SHOPSYSTEM = 'OPERPORT_JIAJU_SHOP_SHOPSYSTEM';

// 运营后台 家居 商家管理 管理账号 梅永坚
export const OPERPORT_JIAJU_SHOP_ACCOUNTLIST = 'OPERPORT_JIAJU_SHOP_ACCOUNTLIST';

// 运营后台 家居 商家管理 新建账号 梅永坚
export const OPERPORT_JIAJU_SHOP_ADDACCOUNT = 'OPERPORT_JIAJU_SHOP_ADDACCOUNT';

// 运营后台 家居 商家管理 编辑账号 梅永坚
export const OPERPORT_JIAJU_SHOP_EDITACCOUNT = 'OPERPORT_JIAJU_SHOP_EDITACCOUNT';

// 运营后台 家居 商家管理 重置密码 梅永坚
export const OPERPORT_JIAJU_SHOP_RESETACCOUNTPASSWORDS = 'OPERPORT_JIAJU_SHOP_RESETACCOUNTPASSWORDS';

// 运营后台 家居 商家管理 启用/禁用 梅永坚
export const OPERPORT_JIAJU_SHOP_ACTIVATEACCOUNT = 'OPERPORT_JIAJU_SHOP_ACTIVATEACCOUNT';

// 运营后台 家居 商家管理 设置权限 梅永坚
export const OPERPORT_JIAJU_SHOP_ACCOUNTAUTHORIZATION = 'OPERPORT_JIAJU_SHOP_ACCOUNTAUTHORIZATION';

// 运营后台 家居 商家管理 删除 梅永坚
export const OPERPORT_JIAJU_SHOP_DELETEACCOUNT = 'OPERPORT_JIAJU_SHOP_DELETEACCOUNT';

// 运营后台 家居 商家管理 设为管理员 梅永坚
export const OPERPORT_JIAJU_SHOP_ACCOUNTADMINISTATORSETTING = 'OPERPORT_JIAJU_SHOP_ACCOUNTADMINISTATORSETTING';

// 运营后台 家居 分类管理 查看列表 梅永坚
export const OPERPORT_JIAJU_SHOPCATEGORY_LIST = 'OPERPORT_JIAJU_SHOPCATEGORY_LIST';

// 运营后台 家居 分类管理 新增分类 梅永坚
export const OPERPORT_JIAJU_SHOPCATEGORY_ADD = 'OPERPORT_JIAJU_SHOPCATEGORY_ADD';

// 运营后台 家居 分类管理 编辑分类 梅永坚
export const OPERPORT_JIAJU_SHOPCATEGORY_EDIT = 'OPERPORT_JIAJU_SHOPCATEGORY_EDIT';

// 运营后台 家居 分类管理 删除分类 梅永坚
export const OPERPORT_JIAJU_SHOPCATEGORY_DELETE = 'OPERPORT_JIAJU_SHOPCATEGORY_DELETE';

// 运营后台 家居 项目管理 查看项目列表 梅永坚
export const OPERPORT_JIAJU_COMMUNITY_LIST = 'OPERPORT_JIAJU_COMMUNITY_LIST';

// 运营后台 家居 项目管理 家居项目配置 梅永坚
export const OPERPORT_JIAJU_COMMUNITY_SETTING = 'OPERPORT_JIAJU_COMMUNITY_SETTING';

// 运营后台 家居 项目管理 商家排序规则设置 梅永坚
export const OPERPORT_JIAJU_COMMUNITY_SORTRULESETTING = 'OPERPORT_JIAJU_COMMUNITY_SORTRULESETTING';

// 运营后台 家居 项目管理 设置商家排序 梅永坚
export const OPERPORT_JIAJU_COMMUNITY_SHOPSORTETTING = 'OPERPORT_JIAJU_COMMUNITY_SHOPSORTETTING';

// 运营后台 家居 批量新增 批量导入商家 梅永坚
export const OPERPORT_JIAJU_BATCHADDING_ADDSHOP = 'OPERPORT_JIAJU_BATCHADDING_ADDSHOP';

// 运营后台 家居 批量新增 批量导入账号 梅永坚
export const OPERPORT_JIAJU_BATCHADDING_ADDACCOUN = 'OPERPORT_JIAJU_BATCHADDING_ADDACCOUN';

// 运营后台 家居 会员管理 查看列表 梅永坚
export const OPERPORT_JIAJU_USER_LIST = 'OPERPORT_JIAJU_USER_LIST';

// 运营后台 家居 会员管理 查看详情 梅永坚
export const OPERPORT_JIAJU_USER_DETAILS = 'OPERPORT_JIAJU_USER_DETAILS';

// 运营后台 家居 会员管理 新增会员 梅永坚
export const OPERPORT_JIAJU_USER_ADD = 'OPERPORT_JIAJU_USER_ADD';

// 运营后台 家居 会员管理 导入会员 梅永坚
export const OPERPORT_JIAJU_USER_BATCHADD = 'OPERPORT_JIAJU_USER_BATCHADD';

// 运营后台 家居 会员管理 导出会员 梅永坚
export const OPERPORT_JIAJU_USER_EXPORT = 'OPERPORT_JIAJU_USER_EXPORT';

// 运营后台 家居 会员管理 编辑 梅永坚
export const OPERPORT_JIAJU_USER_EDIT = 'OPERPORT_JIAJU_USER_EDIT';

// 运营后台 家居 会员管理 激活 梅永坚
export const OPERPORT_JIAJU_USER_ACTIVATE = 'OPERPORT_JIAJU_USER_ACTIVATE';

// 运营后台 家居 会员管理 冻结 梅永坚
export const OPERPORT_JIAJU_USER_FREEZE = 'OPERPORT_JIAJU_USER_FREEZE';

// 运营后台 家居 会员管理 重置密码 梅永坚
export const OPERPORT_JIAJU_USER_RESETPASSWORDS = 'OPERPORT_JIAJU_USER_RESETPASSWORDS';

// 运营后台 家居 会员管理 发短信 梅永坚
export const OPERPORT_JIAJU_USER_SENDMESSAGE = 'OPERPORT_JIAJU_USER_SENDMESSAGE';

// 运营后台 家居 会员管理 查看订单 梅永坚
export const OPERPORT_JIAJU_USER_ORDERVIEW = 'OPERPORT_JIAJU_USER_ORDERVIEW';

// 运营后台 家居 会员管理 操作日志 梅永坚
export const OPERPORT_JIAJU_USER_OPERATIONGLOG = 'OPERPORT_JIAJU_USER_OPERATIONGLOG';

// 运营后台 家居 会员管理 发优惠券 梅永坚
export const OPERPORT_JIAJU_USER_ISSUECOUPONS = 'OPERPORT_JIAJU_USER_ISSUECOUPONS';

// 运营后台 家居 订单列表 查看列表 周文元
export const OPERPORT_JIAJU_ORDERLIST_LIST = 'OPERPORT_JIAJU_ORDERLIST_LIST';

// 运营后台 家居 订单列表 导出 周文元
export const OPERPORT_JIAJU_ORDERLIST_EXPORT = 'OPERPORT_JIAJU_ORDERLIST_EXPORT';

// 运营后台 家居 订单列表 查看详情 周文元
export const OPERPORT_JIAJU_ORDERLIST_DETAILS = 'OPERPORT_JIAJU_ORDERLIST_DETAILS';

// 运营后台 家居 订单列表 取消订单 周文元
export const OPERPORT_JIAJU_ORDERLIST_CLOSE = 'OPERPORT_JIAJU_ORDERLIST_CLOSE';

// 运营后台 家居 订单列表 审核订单 周文元
export const OPERPORT_JIAJU_ORDERLIST_CHECK = 'OPERPORT_JIAJU_ORDERLIST_CHECK';

// 运营后台 家居 订单列表 修改金额 周文元
export const OPERPORT_JIAJU_ORDERLIST_CHANGEAMOUNT = 'OPERPORT_JIAJU_ORDERLIST_CHANGEAMOUNT';

// 运营后台 家居 订单列表 确认发货 周文元
export const OPERPORT_JIAJU_ORDERLIST_DELIVERY = 'OPERPORT_JIAJU_ORDERLIST_DELIVERY';

// 运营后台 家居 订单列表 修改物流 周文元
export const OPERPORT_JIAJU_ORDERLIST_MODIFYLOGISTICS = 'OPERPORT_JIAJU_ORDERLIST_MODIFYLOGISTICS';

// 运营后台 家居 订单列表 备注商品 周文元
export const OPERPORT_JIAJU_ORDERLIST_REMARKGOODS = 'OPERPORT_JIAJU_ORDERLIST_REMARKGOODS';

// 运营后台 家居 订单列表 添加备注 周文元
export const OPERPORT_JIAJU_ORDERLIST_ADDNOTES = 'OPERPORT_JIAJU_ORDERLIST_ADDNOTES';

// 运营后台 家居 订单列表 确认收货 周文元
export const OPERPORT_JIAJU_ORDERLIST_SIGN = 'OPERPORT_JIAJU_ORDERLIST_SIGN';

// 运营后台 家居 订单详情 增加支付 周文元
export const OPERPORT_JIAJU_ORDERDETAILS_ADDPAYMENT = 'OPERPORT_JIAJU_ORDERDETAILS_ADDPAYMENT';

// 运营后台 家居 订单详情 修改支付状态 周文元
export const OPERPORT_JIAJU_ORDERDETAILS_MODIFYPAYMENT = 'OPERPORT_JIAJU_ORDERDETAILS_MODIFYPAYMENT';

// 运营后台 家居 订单详情 修改地址 周文元
export const OPERPORT_JIAJU_ORDERDETAILS_MODIFYADDRESS = 'OPERPORT_JIAJU_ORDERDETAILS_MODIFYADDRESS';

// 运营后台 家居 订单详情 修改发票 周文元
export const OPERPORT_JIAJU_ORDERDETAILS_MODIFYINVOICE = 'OPERPORT_JIAJU_ORDERDETAILS_MODIFYINVOICE';


// 运营后台 家居 流水对账 查看
// export const OPERPORT_JIAJU_ORDERLIST_LIST = 'OPERPORT_JIAJU_ORDERLIST_LIST';

// 运营后台 家居 流水对账 导出
// export const OPERPORT_JIAJU_ORDERLIST_EXPORT = 'OPERPORT_JIAJU_ORDERLIST_EXPORT';

// 运营后台 家居 电子收据 查看列表
// export const OPERPORT_JIAJU_ECRECEIPT_LIST =
//   'OPERPORT_JIAJU_ECRECEIPT_LIST';

// // 运营后台 家居 电子收据 开具收据
// export const OPERPORT_JIAJU_ORDERLIST_RECEIPT = 'OPERPORT_JIAJU_ORDERLIST_RECEIPT';

// // 运营后台 家居 电子收据 导出
// // export const OPERPORT_JIAJU_ORDERLIST_EXPORT = 'OPERPORT_JIAJU_ORDERLIST_EXPORT';

// // 运营后台 家居 联单活动 查看列表
// // export const OPERPORT_JIAJU_ORDERLIST_LIST = 'OPERPORT_JIAJU_ORDERLIST_LIST';

// // 运营后台 家居 联单活动 新建活动
// export const OPERPORT_JIAJU_ORDERLIST_ADD = 'OPERPORT_JIAJU_ORDERLIST_ADD';

// // 运营后台 家居 联单活动 编辑活动
// export const OPERPORT_JIAJU_ORDERLIST_EDIT = 'OPERPORT_JIAJU_ORDERLIST_EDIT';

// // 运营后台 家居 联单活动 查看订单
// export const OPERPORT_JIAJU_ORDERLIST_ORDER = 'OPERPORT_JIAJU_ORDERLIST_ORDER';

// 运营后台 家居 联单活动 导出
// export const OPERPORT_JIAJU_ORDERLIST_EXPORT = 'OPERPORT_JIAJU_ORDERLIST_EXPORT';

// 运营后台 家居 流水对账 查看 820
export const OPERPORT_JIAJU_ACCOUNTS_LIST = 'OPERPORT_JIAJU_ACCOUNTS_LIST';

// 运营后台 家居 流水对账 导出 820
export const OPERPORT_JIAJU_ACCOUNTS_EXPORT = 'OPERPORT_JIAJU_ACCOUNTS_EXPORT';

// 运营后台 家居 电子收据 查看列表 831
export const OPERPORT_JIAJU_ECRECEIPT_LIST = 'OPERPORT_JIAJU_ECRECEIPT_LIST';

// 运营后台 家居 电子收据 开具收据 831
export const OPERPORT_JIAJU_ECRECEIPT_RECEIPT = 'OPERPORT_JIAJU_ECRECEIPT_RECEIPT';

// 运营后台 家居 电子收据 导出 831
export const OPERPORT_JIAJU_ECRECEIPT_EXPORT = 'OPERPORT_JIAJU_ECRECEIPT_EXPORT';

// 运营后台 家居 联单活动 查看列表 917
export const OPERPORT_JIAJU_LIANDANACTIVITY_LIST = 'OPERPORT_JIAJU_LIANDANACTIVITY_LIST';

// 运营后台 家居 联单活动 新建活动 917
export const OPERPORT_JIAJU_LIANDANACTIVITY_ADD = 'OPERPORT_JIAJU_LIANDANACTIVITY_ADD';

// 运营后台 家居 联单活动 编辑活动 917
export const OPERPORT_JIAJU_LIANDANACTIVITY_EDIT = 'OPERPORT_JIAJU_LIANDANACTIVITY_EDIT';

// 运营后台 家居 联单活动 查看订单 917
export const OPERPORT_JIAJU_LIANDANACTIVITY_ORDER = 'OPERPORT_JIAJU_LIANDANACTIVITY_ORDER';

// 运营后台 家居 联单活动 导出 917
export const OPERPORT_JIAJU_LIANDANACTIVITY_EXPORT = 'OPERPORT_JIAJU_LIANDANACTIVITY_EXPORT';

// 家居 家居券退款申请列表 JIAJUQUANRETURNLIST 查看列表 LIST
export const OPERPORT_JIAJU_JIAJUQUANRETURNLIST_LIST = 'OPERPORT_JIAJU_JIAJUQUANRETURNLIST_LIST';
// 家居家居券退款申请列表 JIAJUQUANRETURNLIST 审核 APPROVE
export const OPERPORT_JIAJU_JIAJUQUANRETURNLIST_APPROVE = 'OPERPORT_JIAJU_JIAJUQUANRETURNLIST_APPROVE';
// 家居 家居券退款申请列表 JIAJUQUANRETURNLIST 同步 SYNC
export const OPERPORT_JIAJU_JIAJUQUANRETURNLIST_SYNC = 'OPERPORT_JIAJU_JIAJUQUANRETURNLIST_SYNC';
// 家居 家居券退款申请日志 JIAJUQUANRETURNLOG 查看列表 LIST
export const OPERPORT_JIAJU_JIAJUQUANRETURNLOG_LIST = 'OPERPORT_JIAJU_JIAJUQUANRETURNLOG_LIST';
